/* ==========================================================================
   VERONICA SALA — PILATES & MOVEMENT ARCHITECTURE
   Application Logic, Multilingual Engine & Smart Calendly Funnel
   ========================================================================== */

const i18n = {
  "it": {
    "announcement_text": "Aperte le prenotazioni per le sessioni private a Lisbona (Matwork, Reformer e a Domicilio)",
    "nav_about": "Chi Sono",
    "nav_method": "Il Metodo",
    "nav_services": "Sessioni",
    "nav_rates": "Listino",
    "nav_gallery": "Galleria",
    "nav_ecosystem": "Ecosistema",
    "nav_location": "Lisbona",
    "nav_quiz_btn": "Trova la Tua Sessione",
    "hero_eyebrow": "Certificata STOTT Pilates® · Ex Ballerina Professionista",
    "hero_title_1": "Dove la Disciplina della Danza",
    "hero_title_italic": "Incontra la Precisione del Reformer.",
    "hero_lead": "Formata alla Hamburg Ballet Academy ed ex ballerina professionista a Berlino. Unisco la forza fondamentale del Pilates Matwork alla precisione biomeccanica del Reformer a Lisbona.",
    "hero_cta_primary": "Prenota Sessione Privata 1:1",
    "hero_cta_secondary": "Scopri il Metodo ↓",
    "cred_years": "Anni di Padronanza del Movimento",
    "cred_stott": "Standard Aureo della Biomeccanica",
    "cred_langs": "Lingue Parlate (IT·EN·DE·PT)",
    "trust_title": "FONDAMENTA DI ECCELLENZA",
    "hero_badge_title": "Studio & a Domicilio a Lisbona",
    "hero_badge_sub": "Matwork · Reformer · Chiado · Saldanha",
    "hero_quote": "\"Il movimento non è semplice esercizio; è il ripristino architettonico del tuo allineamento scheletrico, della forza profonda e della consapevolezza corporea.\"",
    "about_tag": "L'ARTISTA DIETRO IL METODO",
    "about_title_1": "Dal Palcoscenico Tedesco",
    "about_title_2": "alla Pratica di Pilates più Completa di Lisbona.",
    "about_p1": "Nata a Milano e perfezionata alla celebre Hamburg Ballet Academy, Veronica ha lavorato per anni come ballerina professionista nelle principali produzioni teatrali e contemporanee di Berlino (tra cui il prestigioso Friedrichstadt-Palast).",
    "about_p2": "Dopo aver scoperto come il Pilates abbia trasformato la sua longevità atletica e la prevenzione degli infortuni, ha conseguito la certificazione STOTT Pilates®—padroneggiando sia il Matwork a corpo libero con piccoli attrezzi che l'apparato con molle del Reformer. Oggi a Lisbona unisce la grazia dell'arte coreutica alla biomeccanica avanzata.",
    "about_float_title": "L'Anatomia di una Ballerina",
    "about_float_desc": "Anni di rigorosa formazione classica in Germania offrono a Veronica un occhio microscopico per cogliere asimmetrie e micro-compensi posturali sia su tappetino che su macchinario.",
    "time_1_title": "Hamburg Ballet Academy",
    "time_1_desc": "Rigorosa disciplina classica, intelligenza spaziale e padronanza biomeccanica.",
    "time_2_title": "Palcoscenico Professionale a Berlino",
    "time_2_desc": "Performance ai massimi livelli europei; profonda comprensione della longevità corporea.",
    "time_3_title": "Certificazione STOTT Pilates® & Studio a Lisbona",
    "time_3_desc": "Insegnamento di livello riabilitativo, coaching privato e formati dinamici in studio.",
    "method_tag": "L'ARCHITETTURA FONDAMENTALE",
    "method_title": "Matwork & Reformer: Lo Spettro Completo",
    "method_subtitle": "Il vero Pilates unisce il controllo gravitazionale a corpo libero alla resistenza dinamica e alla decompressione spinale delle molle del Reformer.",
    "m1_title": "Allineamento Posturale Microscopico",
    "m1_desc": "Individuazione e correzione millimetrica di disallineamenti del bacino, della colonna e del collo prima che diventino dolore cronico.",
    "m1_tag": "Salute Scheletrica",
    "m2_title": "Matwork & Piccoli Attrezzi",
    "m2_desc": "Controllo del peso corporeo, Magic Circle, foam roller e bande elastiche per la massima connessione del core profondo.",
    "m2_tag": "Architettura del Core",
    "m3_title": "Meccanica delle Molle Reformer",
    "m3_desc": "Utilizzo della resistenza progressiva del carrello per decomprimere le articolazioni e allungare le catene muscolari.",
    "m3_tag": "Tensione & Fluidità",
    "m4_title": "Accoglienza Multilingue",
    "m4_desc": "Istruzioni fluide in Italiano, Tedesco, Inglese e Portoghese. Ideale per residenti ed expat a Lisbona.",
    "m4_tag": "Internazionale",
    "sessions_tag": "FORMATI SU MISURA",
    "sessions_title": "Scegli il Tuo Percorso di Movimento",
    "quiz_trigger_btn": "Fai il Quiz di 30 Secondi",
    "badge_most_exclusive": "PIÙ RICHIESTO & SU MISURA",
    "s1_sub": "Studio Privato / A Domicilio / Online",
    "s1_title": "1-a-1 Matwork & Reformer",
    "s1_desc": "Sessione personalizzata di 55 minuti che combina lavoro su tappetino, piccoli attrezzi e Reformer adattati alla tua postura.",
    "s1_f1": "Valutazione Posturale Iniziale Dettagliata",
    "s1_f2": "Repertorio Ibrido Matwork e Reformer Completo",
    "s1_f3": "Sollievo Mirato per Dolori a Schiena e Collo",
    "s1_f4": "In Italiano, Tedesco, Inglese o Portoghese",
    "btn_book_private": "Prenota Sessione 1:1",
    "s2_sub": "Semi-Privato (2 Persone)",
    "s2_title": "Esperienza Pilates Duet",
    "s2_desc": "Condividi la tua lezione con un partner o un'amica su mat o reformer. Ricevi attenzioni personalizzate condividendo energia e costi.",
    "s2_f1": "Progressione Sincronizzata del Movimento",
    "s2_f2": "Aggiustamenti Personalizzati per Entrambi",
    "s2_f3": "Perfetto per Coppie o Amici",
    "s2_f4": "Disponibile in Studio o a Domicilio",
    "btn_book_duet": "Richiedi Duet",
    "s3_sub": "Studi Prescription Lisbona",
    "s3_title": "Signature Dynamic Reformer",
    "s3_desc": "Sessioni di gruppo ad alta intensità a ritmo di musica, focalizzate su resistenza, forza del core e fluidità dinamica.",
    "s3_f1": "Playlist Curate ad Alta Energia",
    "s3_f2": "Flusso Dinamico Intermedio e Avanzato",
    "s3_f3": "Disponibile a Saldanha, Alcântara e São Bento",
    "s3_f4": "Prenotabile su ClassPass e Momence",
    "btn_view_schedule": "Vedi Orari in Studio",
    "price_from": "Da",
    "price_per_sess": "/ sessione",
    "price_per_pers": "/ persona",
    "price_studio_pack": "Pack Studio",
    "price_per_class": "/ lezione",
    "rates_tag": "INVESTIMENTO NEL TUO CORPO",
    "rates_title": "Listino Trasparente & Pacchetti",
    "rates_subtitle": "Tutte le sessioni private includono monitoraggio posturale, massima igiene delle attrezzature e scheda su misura.",
    "th_format": "Formato Percorso",
    "th_freq": "Frequenza",
    "th_langs": "Lingue",
    "th_rate": "Tariffa",
    "th_action": "Azione",
    "r1_title": "Singola Sessione di Valutazione Posturale",
    "r1_desc": "Ideale per iniziare, valutare l'allineamento della colonna e definire gli obiettivi (Mat o Reformer).",
    "r1_freq": "Sessione singola da 60 min",
    "r1_langs": "IT · EN · DE · PT",
    "btn_book_trial": "Prenota Prova",
    "r2_title": "Pacchetto 5 Sessioni Private 1:1",
    "r2_desc": "Percorso intensivo di riallineamento e rafforzamento profondo con cadenza settimanale.",
    "r2_freq": "5 sessioni private da 55 min",
    "r2_langs": "IT · EN · DE · PT",
    "btn_select_pack": "Scegli Pack",
    "r3_title": "Pacchetto 10 Sessioni Complete",
    "r3_desc": "Il programma completo di trasformazione posturale, coordinazione e forza atletica (Include piano casa).",
    "r3_freq": "10 sessioni private da 55 min",
    "r3_langs": "IT · EN · DE · PT",
    "r4_title": "Sessione Duet (2 Persone)",
    "r4_desc": "Sessione semi-privata per due persone con programma coordinato.",
    "r4_freq": "Per persona / sessione",
    "r4_langs": "IT · EN · DE · PT",
    "btn_book_duet_row": "Prenota Duet",
    "gallery_tag": "ARCHITETTURA VISIVA & INSTAGRAM",
    "gallery_title": "Movimento, Ritmo e Precisione a Lisbona",
    "gallery_subtitle": "Sequenze reali su Reformer, biomeccanica posturale e pratica quotidiana in studio di Veronica.",
    "g1_tag": "Reformer Flow",
    "g1_title": "Tensione Dinamica e Allineamento Articolare",
    "g2_tag": "Architettura del Core",
    "g2_title": "Attivazione Addominale Profonda e Pavimento Pelvico",
    "g3_tag": "Matwork & Colonna",
    "g3_title": "Articolazione Segmentale Vertebrale",
    "g4_tag": "Neuromuscolare",
    "g4_title": "I Micro-Aggiustamenti Posturali della Ballerina",
    "g5_tag": "Dinamica delle Molle",
    "g5_title": "Decompressione e Resistenza Controllata STOTT",
    "g6_tag": "Studio a Lisbona",
    "g6_title": "Energia, Ritmo e Fluidità Trasformativa",
    "gallery_btn_text": "Segui Veronica su Instagram @salaveronica",
    "eco_tag": "ECOSISTEMA & BENESSERE",
    "eco_title": "Oltre la Singola Sessione",
    "pod_badge": "Nuovo Podcast",
    "pod_title": "Podcast: The Mind & Movement",
    "pod_desc": "Episodi brevi quindicinali di Veronica sull'anatomia applicata, il recupero da infortuni e la respirazione.",
    "pod_ep": "Ep. 04: Perché la Postura Influisce sulla tua Energia Quotidiana (18 min)",
    "pod_link": "Ascolta su Spotify & Apple →",
    "gear_badge": "Essenziali Studio",
    "gear_title": "Attrezzatura & Accessori Curati",
    "gear_desc": "I calzini grip ad alta aderenza e gli accessori raccomandati da Veronica per la massima igiene e trazione su Reformer.",
    "gear_link": "Vedi Essenziali Consigliati →",
    "priv_badge": "Collaborazioni & Cura",
    "priv_title": "Agevolazioni per Artisti & Sanitari",
    "priv_desc": "Sconto cortesia del 15% sulle sessioni private dedicato a ballerini professionisti, attori e operatori sanitari.",
    "priv_link": "Richiedi Tariffa Agevolata →",
    "test_tag": "ESPERIENZE DEI CLIENTI",
    "test_title": "La Voce di chi si Allena a Lisbona",
    "t1_text": "\"Essendo un'expat a Lisbona, trovare un'insegnante certificata STOTT che parla perfettamente e ha un vero background di danza è stato un sogno. Il mio mal di schiena lombare da scrivania è sparito in 6 sessioni.\"",
    "t1_role": "Dirigente Tech & Expat, Lisbona",
    "t2_text": "\"I comandi verbali di Veronica sono unici. Senti subito la sua formazione da ballerina: ogni millimetro di postura viene corretto. Il lavoro muscolare è intenso, ma l'eleganza è impareggiabile.\"",
    "t2_role": "Architetto, Chiado",
    "t3_text": "\"La sua energia al Reformer da Prescription è contagiosa, ma le sessioni private 1-a-1 hanno portato il mio recupero atletico a un altro livello. Insegnamento di livello mondiale.\"",
    "t3_role": "Triatleta, Cascais",
    "loc_tag": "DOVE FARE LEZIONE A LISBONA",
    "loc_title_1": "Centro di Lisbona",
    "loc_title_2": "In Studio o nella tua Residenza.",
    "loc_p": "Le sessioni private 1-a-1 si svolgono in spazi boutique a Lisbona (Saldanha, Chiado, Santos) o a domicilio su appuntamento.",
    "loc_1_title": "Studi Prescription (Gruppo & Dinamico)",
    "loc_1_desc": "Saldanha · Alcântara · São Bento · Parque das Nações",
    "loc_2_title": "Studio Privato 1-a-1",
    "loc_2_desc": "Spazio boutique riservato con Reformer per la massima privacy.",
    "loc_3_title": "A Domicilio / Cascais & Lisbona",
    "loc_3_desc": "Sessioni personalizzate di Matwork e piccoli attrezzi a casa tua.",
    "map_title": "Mappa degli Studi a Lisbona",
    "map_badge": "Attivo Ora",
    "map_footer": "I messaggi diretti su WhatsApp ricevono risposta entro 2 ore.",
    "contact_tag": "CONTATTO DIRETTO",
    "contact_title": "Inizia la tua Trasformazione Posturale",
    "contact_p": "Vuoi sperimentare la precisione di un'ex ballerina professionista? Scrivi direttamente a Veronica per condividere i tuoi obiettivi e concordare una data.",
    "ch_1_title": "Risposta Più Rapida su WhatsApp",
    "ch_1_desc": "Chat diretta per concordare gli orari in modo semplice.",
    "ch_2_title": "Lingue Parlate",
    "ch_2_desc": "Italiano, Tedesco (Deutsch), Inglese (English), Portoghese (Português)",
    "wa_btn_text": "Scrivi a Veronica su WhatsApp",
    "form_title": "Richiedi una Valutazione",
    "form_subtitle": "Compila le tue preferenze e ricevi le disponibilità orarie entro 24 ore.",
    "lbl_name": "Il Tuo Nome",
    "lbl_email": "Indirizzo Email",
    "lbl_phone": "WhatsApp / Telefono",
    "lbl_interest": "Formato Sessione Desiderato",
    "opt_private": "Sessione Privata 1-a-1 Matwork & Reformer",
    "opt_duet": "Sessione Duet (2 Persone)",
    "opt_trial": "Valutazione Posturale Iniziale di Prova",
    "opt_studio": "Classi di Gruppo presso Prescription",
    "lbl_lang_pref": "Lingua di Insegnamento Preferita",
    "lbl_notes": "Obiettivi, Domande o Storico di Infortuni",
    "btn_submit_form": "Invia Richiesta di Contatto →",
    "modal_tag": "QUIZ IN 30 SECONDI",
    "modal_title": "Trova il Tuo Percorso di Pilates Ideale",
    "modal_subtitle": "Rispondi a 2 veloci domande per scoprire se il percorso Privato 1:1, Duet o Studio Dinamico fa al caso tuo.",
    "q1_title": "1. Qual è il tuo obiettivo primario di movimento?",
    "q1_opt1": "Salute della Colonna & Allineamento Posturale",
    "q1_opt2": "Forza del Core & Condizionamento Atletico",
    "q1_opt3": "Energia Dinamica & Ritmo con la Musica",
    "q2_title": "2. Che esperienza hai con il macchinario Reformer?",
    "q2_opt1": "Principiante Assoluto / Prima Volta",
    "q2_opt2": "Qualche esperienza con Matwork o Reformer",
    "q2_opt3": "Avanzato / Ex ballerino o atleta",
    "res_badge": "IL PERCORSO RACCOMANDATO PER TE",
    "modal_btn": "Procedi a Prenotare la Sessione Raccomandata →",
    "footer_desc": "Hamburg Ballet Academy · Palcoscenici di Berlino · Certificata STOTT Pilates®. Pratica Privata e in Studio a Lisbona, Portogallo.",
    "foot_nav_title": "Navigazione",
    "foot_nav_about": "Chi Sono",
    "foot_nav_method": "Il Metodo",
    "foot_nav_sessions": "Formati Privati & Studio",
    "foot_nav_rates": "Listino & Pacchetti",
    "foot_nav_eco": "Podcast & Accessori",
    "foot_loc_title": "Sedi & Studi",
    "foot_loc_sal": "Prescription Saldanha",
    "foot_loc_alc": "Prescription Alcântara",
    "foot_loc_chi": "Studio Privato Chiado",
    "foot_loc_cas": "A Domicilio / Lisbona & Cascais",
    "foot_social_title": "Segui & Connettiti",
    "foot_soc_wa": "WhatsApp Diretto",
    "foot_soc_ig": "Instagram @salaveronica",
    "foot_soc_fb": "Facebook",
    "foot_lang_note": "Lezioni guidate con padronanza in Italiano, Tedesco, Inglese e Portoghese.",
    "foot_copy": "© 2026 Veronica Sala. Tutti i diritti riservati. Movement Architecture & STOTT Pilates.",
    "foot_crafted": "Realizzato con precisione per Veronica Sala",
    "r1_badge": "Consigliato per Iniziare",
    "eco_subtitle": "Dalla divulgazione audio agli accessori curati per la pratica quotidiana.",
    "pod_track": "Ascolta Anteprima Audio (1:30 min)",
    "shop_badge": "Attrezzatura Curata",
    "shop_title": "Studio Essentials & Grip Gear",
    "shop_desc": "Calzini grip ad alta aderenza e teli antiscivolo per Reformer selezionati da Veronica.",
    "shop_link": "Scopri gli Accessori Consigliati →",
    "tab_calendar": "Calendario Interattivo (Calendly)",
    "tab_whatsapp": "Prenotazione Rapida WhatsApp",
    "ch_sync_title": "Sincronizzazione Calendario Istantanea",
    "ch_sync_desc": "Invito automatico su Google / Apple Calendar con promemoria.",
    "cal_badge_note": "Disponibilità in Tempo Reale: Chiado, Saldanha & Domicilio",
    "cal_default_badge": "Sessione Privata 1:1 Matwork & Reformer",
    "cal_step1_title": "Seleziona Data e Fascia Oraria",
    "cal_lbl_date": "Scegli il Giorno (Settembre / Ottobre 2026)",
    "cal_lbl_time": "Orari Disponibili a Lisbona (WEST)",
    "cal_lbl_loc": "Sede o Modalità Sessione",
    "opt_loc_chiado": "Studio Privato Chiado (Sala Reformer Riservata)",
    "opt_loc_saldanha": "Prescription Saldanha",
    "opt_loc_inhome": "A Domicilio (Lisbona & Cascais)",
    "opt_loc_online": "Consulenza Video Online (Zoom)",
    "btn_confirm_booking": "Conferma & Prenota su Calendly →",
    "wa_view_title": "Messaggio Diretto Veloce",
    "wa_view_sub": "Preferisci chattare direttamente? Scrivi le tue esigenze e invia su WhatsApp.",
    "btn_send_wa": "Apri Chat WhatsApp Diretta",
    "r2_badge": "Pacchetto 5",
    "r3_badge": "Pacchetto 10",
    "r4_badge": "Duetto (2 Persone)"
  },
  "en": {
    "announcement_text": "Now Booking Autumn Private Sessions in Lisbon (Matwork, Reformer & In-Home)",
    "nav_about": "About",
    "nav_method": "The Method",
    "nav_services": "Sessions",
    "nav_rates": "Rates",
    "nav_gallery": "Gallery",
    "nav_ecosystem": "Ecosystem",
    "nav_location": "Lisbon",
    "nav_quiz_btn": "Find Your Session",
    "hero_eyebrow": "STOTT Pilates® Certified · Former Dancer",
    "hero_title_1": "Where Ballet Discipline",
    "hero_title_italic": "Meets Classical & Reformer Pilates.",
    "hero_lead": "Trained at the Hamburg Ballet Academy and a former professional dancer in Berlin. Bridging the foundational power of Pilates Matwork with the dynamic precision of the Reformer machine in Lisbon.",
    "hero_cta_primary": "Book Private 1:1 Session",
    "hero_cta_secondary": "Discover The Method ↓",
    "cred_years": "Years Stage & Movement Mastery",
    "cred_stott": "Gold Standard Biomechanics",
    "cred_langs": "Fluent Languages (EN·DE·PT·IT)",
    "trust_title": "FOUNDATIONS OF EXCELLENCE",
    "hero_badge_title": "Lisbon Studio & In-Home",
    "hero_badge_sub": "Matwork · Reformer · Chiado · Saldanha",
    "hero_quote": "\"Movement is not just exercise; it is an architectural restoration of your skeletal alignment, core power, and body awareness.\"",
    "about_tag": "THE ARTIST BEHIND THE METHOD",
    "about_title_1": "From the German Stage",
    "about_title_2": "to Lisbon's Most Complete Pilates Practice.",
    "about_p1": "Born in Milan and shaped by the world-renowned Hamburg Ballet Academy, Veronica spent years performing as a professional dancer in Berlin's elite contemporary and theatre productions (including the prestigious Friedrichstadt-Palast).",
    "about_p2": "After discovering how Pilates revolutionized her own physical longevity and injury resilience, she completed the comprehensive STOTT Pilates® certification—mastering both classical floor Matwork with props and heavy spring-loaded Reformer apparatus. Today, as a lead trainer in Lisbon, she bridges the grace of classical stage artistry with contemporary sports science.",
    "about_float_title": "Anatomy of a Dancer",
    "about_float_desc": "Years of rigorous classical training in Germany give Veronica a microscopic eye for postural asymmetries and micro-compensation on both mat and machine.",
    "time_1_title": "Hamburg Ballet Academy",
    "time_1_desc": "Rigorous classical foundation, spatial intelligence & biomechanical mastery.",
    "time_2_title": "Berlin Professional Stage",
    "time_2_desc": "Performing at world-class levels; understanding body longevity and injury recovery.",
    "time_3_title": "STOTT Pilates® & Lisbon Practice",
    "time_3_desc": "Comprehensive Matwork, props, reformer coaching & dynamic group formats.",
    "method_tag": "THE CORE ARCHITECTURE",
    "method_title": "Matwork & Reformer: The Complete Spectrum",
    "method_subtitle": "True Pilates combines the pure gravitational control of floor Matwork with the spring resistance and spinal decompression of the Reformer.",
    "m1_title": "Microscopic Postural Alignment",
    "m1_desc": "Detecting and correcting pelvic tilts, spinal imbalances, and neck strain before they turn into chronic pain.",
    "m1_tag": "Skeletal Health",
    "m2_title": "Matwork & Precision Props",
    "m2_desc": "Mastering bodyweight gravity, Magic Circles, foam rollers, and resistance bands for pure core connection.",
    "m2_tag": "Core Architecture",
    "m3_title": "Reformer Spring Mechanics",
    "m3_desc": "Utilizing carriage resistance for joint decompression, lengthening, and progressive athletic loading.",
    "m3_tag": "Flow & Tension",
    "m4_title": "Multilingual Warmth",
    "m4_desc": "Seamless cues in English, German, Portuguese, or Italian. Perfect for Lisbon's international community.",
    "m4_tag": "Expat Friendly",
    "sessions_tag": "TAILORED FORMATS",
    "sessions_title": "Choose Your Movement Journey",
    "quiz_trigger_btn": "Take the 30-sec Match Quiz",
    "badge_most_exclusive": "MOST POPULAR & BESPOKE",
    "s1_sub": "Private Studio / In-Home / Online",
    "s1_title": "1-on-1 Matwork & Reformer",
    "s1_desc": "A completely customized 55-minute session combining floor matwork, precision props, and reformer apparatus tailored to your spine.",
    "s1_f1": "Comprehensive Initial Postural Assessment",
    "s1_f2": "Hybrid Matwork & Full Reformer Repertoire",
    "s1_f3": "Targeted Chronic Back/Neck Pain Relief",
    "s1_f4": "English, German, Portuguese or Italian",
    "btn_book_private": "Book 1:1 Session",
    "s2_sub": "Semi-Private (2 People)",
    "s2_title": "Duet Pilates Experience",
    "s2_desc": "Share your practice with a partner or friend on mat or reformer. Enjoy high-touch personal cues while sharing the energy and cost.",
    "s2_f1": "Synchronized Movement Progression",
    "s2_f2": "Personalized Adjustments for Both",
    "s2_f3": "Great for Couples or Friends",
    "s2_f4": "Available in Studio or In-Home",
    "btn_book_duet": "Inquire Duet",
    "s3_sub": "Prescription Lisbon Studios",
    "s3_title": "Signature Dynamic Reformer",
    "s3_desc": "High-intensity, music-driven group reformer sessions focusing on endurance, core strength and dynamic flow.",
    "s3_f1": "High-Energy Curated Playlists",
    "s3_f2": "Intermediate & Advanced Dynamic Flow",
    "s3_f3": "Available in Saldanha, Alcântara & São Bento",
    "s3_f4": "Bookable on ClassPass & Momence",
    "btn_view_schedule": "View Studio Schedule",
    "price_from": "From",
    "price_per_sess": "/ session",
    "price_per_pers": "/ person",
    "price_studio_pack": "Studio Pack",
    "price_per_class": "/ class",
    "rates_tag": "INVESTMENT IN YOUR BODY",
    "rates_title": "Transparent Rates & Value Packs",
    "rates_subtitle": "All private sessions include postural tracking, equipment sanitation, and bespoke progression.",
    "th_format": "Program Format",
    "th_freq": "Frequency",
    "th_langs": "Languages",
    "th_rate": "Rate",
    "th_action": "Action",
    "r1_title": "Single Trial & Posture Assessment",
    "r1_desc": "Ideal for first-timers to evaluate spinal alignment & establish goals (Mat or Reformer).",
    "r1_freq": "Single 60-min session",
    "r1_langs": "EN · DE · PT · IT",
    "btn_book_trial": "Book Trial",
    "r2_title": "5 Private Sessions Pack (1:1)",
    "r2_desc": "Intensive postural correction & core rebuilding protocol with dedicated weekly slots.",
    "r2_freq": "5 x 55-min private sessions",
    "r2_langs": "EN · DE · PT · IT",
    "btn_select_pack": "Select Pack",
    "r3_title": "10 Private Sessions Master Pack",
    "r3_desc": "The definitive athletic and skeletal transformation with custom home maintenance routines.",
    "r3_freq": "10 x 55-min private sessions",
    "r3_langs": "EN · DE · PT · IT",
    "r4_title": "Duet Session (2 People)",
    "r4_desc": "Semi-private session for two individuals with synchronized tailored programming.",
    "r4_freq": "Per person / session",
    "r4_langs": "EN · DE · PT · IT",
    "btn_book_duet_row": "Book Duet",
    "gallery_tag": "VISUAL ARCHITECTURE & INSTAGRAM",
    "gallery_title": "Movement, Rhythm & Precision in Lisbon",
    "gallery_subtitle": "Live glimpses into Veronica's Reformer sequences, core biomechanics, and daily studio practice.",
    "g1_tag": "Reformer Flow",
    "g1_title": "Dynamic Tension & Joint Alignment",
    "g2_tag": "Core Architecture",
    "g2_title": "Deep Transverse & Pelvic Precision",
    "g3_tag": "Mat & Spine",
    "g3_title": "Segmental Spinal Articulation",
    "g4_tag": "Neuromuscular",
    "g4_title": "The Dancer's Postural Micro-Cues",
    "g5_tag": "Spring Dynamics",
    "g5_title": "Decompression & Controlled Resistance",
    "g6_tag": "Lisbon Practice",
    "g6_title": "Energy, Rhythm & Empowering Flow",
    "gallery_btn_text": "Follow Veronica on Instagram @salaveronica",
    "eco_tag": "ECOSYSTEM & WELLNESS",
    "eco_title": "Beyond the Individual Session",
    "pod_badge": "New Podcast",
    "pod_title": "The Mind & Movement Podcast",
    "pod_desc": "Fortnightly 15-minute audio capsules by Veronica exploring biomechanics, injury prevention, breathwork & longevity.",
    "pod_ep": "Ep. 04: Why Posture Dictates Your Daily Energy (18 min)",
    "pod_link": "Listen on Spotify & Apple →",
    "gear_badge": "Studio Essentials",
    "gear_title": "Curated Studio Gear",
    "gear_desc": "Veronica's handpicked grip socks, carriage mats & resistance loops engineered for studio safety and grip.",
    "gear_link": "View Recommended Gear →",
    "priv_badge": "Partnership & Care",
    "priv_title": "Artists & Healthcare Privileges",
    "priv_desc": "A dedicated 15% courtesy concession on private sessions for active dancers, theatre performers, and healthcare workers.",
    "priv_link": "Apply for Concession Rate →",
    "test_tag": "CLIENT EXPERIENCES",
    "test_title": "Voices from Lisbon & Beyond",
    "t1_text": "\"As a German expat living in Lisbon, finding a certified STOTT trainer who speaks German and has genuine stage experience was a dream. My chronic lower back pain from desk work disappeared within 6 sessions.\"",
    "t1_role": "Tech Executive & Expat, Lisbon",
    "t2_text": "\"Veronica’s cues are unlike any other instructor. You can immediately feel her classical ballet background—every centimeter of your posture is corrected. The burn is intense, but the elegance is unmatched.\"",
    "t2_role": "Architect, Chiado",
    "t3_text": "\"Her energy on the Reformer at Prescription is legendary, but the 1-on-1 private sessions took my athletic recovery to another dimension. Truly world-class instruction.\"",
    "t3_role": "Triathlete, Cascais",
    "loc_tag": "WHERE TO PRACTICE IN LISBON",
    "loc_title_1": "Central Lisbon",
    "loc_title_2": "At Your Preferred Studio or Home.",
    "loc_p": "Private 1:1 sessions are held in boutique reformer spaces across Lisbon (Saldanha, Chiado, Santos) or directly at your private residence by appointment.",
    "loc_1_title": "Prescription Studios (Group & Dynamic)",
    "loc_1_desc": "Saldanha · Alcântara · São Bento · Parque das Nações",
    "loc_2_title": "Private Studio 1-on-1",
    "loc_2_desc": "Bespoke boutique reformer room with complete privacy.",
    "loc_3_title": "In-Home / Cascais & Lisbon",
    "loc_3_desc": "Private mat & mobile reformer apparatus on request.",
    "map_title": "Lisbon Movement Map",
    "map_badge": "Active Now",
    "map_footer": "Direct WhatsApp booking responds within 2 hours.",
    "contact_tag": "DIRECT INQUIRIES",
    "contact_title": "Start Your Movement Transformation",
    "contact_p": "Ready to experience the precision of a former professional dancer? Send a message directly to Veronica to discuss your goals, check studio availability, or schedule an initial assessment.",
    "ch_1_title": "Fastest Response via WhatsApp",
    "ch_1_desc": "Direct mobile chat for quick schedule coordination.",
    "ch_2_title": "Languages Spoken",
    "ch_2_desc": "English, German (Deutsch), Portuguese (Português), Italian (Italiano)",
    "wa_btn_text": "Message Veronica on WhatsApp",
    "form_title": "Schedule a Consultation",
    "form_subtitle": "Fill in your preferences and receive available time slots within 24h.",
    "lbl_name": "Your Name",
    "lbl_email": "Email Address",
    "lbl_phone": "WhatsApp / Phone",
    "lbl_interest": "Preferred Session Format",
    "opt_private": "1-on-1 Private Reformer Session",
    "opt_duet": "Duet Session (2 people)",
    "opt_trial": "Introductory Assessment & Trial",
    "opt_studio": "Group Classes at Prescription",
    "lbl_lang_pref": "Preferred Instruction Language",
    "lbl_notes": "Goals, Inquiries or Medical History",
    "btn_submit_form": "Send Inquire Request →",
    "modal_tag": "30-SECOND MATCHER",
    "modal_title": "Find Your Perfect Pilates Pathway",
    "modal_subtitle": "Answer 2 quick questions to discover whether Private 1:1, Duet, or Dynamic Studio is right for you.",
    "q1_title": "1. What is your primary movement goal?",
    "q1_opt1": "Spinal Health & Postural Alignment",
    "q1_opt2": "Core Strength & Athletic Conditioning",
    "q1_opt3": "Dynamic Energy & Rhythm with Music",
    "q2_title": "2. What is your experience with Reformer machines?",
    "q2_opt1": "Complete Beginner / First time",
    "q2_opt2": "Some Mat or Reformer experience",
    "q2_opt3": "Advanced / Former dancer or athlete",
    "res_badge": "YOUR RECOMMENDED PATH",
    "modal_btn": "Proceed to Book Recommended Session →",
    "footer_desc": "Hamburg Ballet Academy · Berlin Professional Stage · STOTT Pilates® Certified. Private & Studio Practice in Lisbon, Portugal.",
    "foot_nav_title": "Navigation",
    "foot_nav_about": "About Veronica",
    "foot_nav_method": "The Method",
    "foot_nav_sessions": "Private & Studio Formats",
    "foot_nav_rates": "Rates & Packs",
    "foot_nav_eco": "Podcast & Gear",
    "foot_loc_title": "Locations & Studios",
    "foot_loc_sal": "Prescription Saldanha",
    "foot_loc_alc": "Prescription Alcântara",
    "foot_loc_chi": "Private Studio Chiado",
    "foot_loc_cas": "In-Home Lisbon & Cascais",
    "foot_social_title": "Connect & Follow",
    "foot_soc_wa": "WhatsApp Direct",
    "foot_soc_ig": "Instagram @salaveronica",
    "foot_soc_fb": "Facebook",
    "foot_lang_note": "Classes taught fluently in English, Deutsch, Português & Italiano.",
    "foot_copy": "© 2026 Veronica Sala. All rights reserved. Movement Architecture & STOTT Pilates.",
    "foot_crafted": "Crafted with precision for Veronica Sala",
    "r1_badge": "Recommended to Start",
    "eco_subtitle": "From audio education to curated movement essentials for your daily practice.",
    "pod_track": "Listen to Audio Preview (1:30 min)",
    "shop_badge": "Curated Gear",
    "shop_title": "Studio Essentials & Grip Gear",
    "shop_desc": "High-traction grip socks and non-slip carriage mats handpicked by Veronica.",
    "shop_link": "Explore Recommended Essentials →",
    "tab_calendar": "Interactive Live Calendar (Calendly)",
    "tab_whatsapp": "Fast WhatsApp Booking",
    "ch_sync_title": "Instant Calendar Synchronization",
    "ch_sync_desc": "Direct invite sent to your Google / Apple Calendar with confirmation.",
    "cal_badge_note": "Real-Time Lisbon Studio & In-Home Availability",
    "cal_default_badge": "Private 1-on-1 Reformer Session",
    "cal_step1_title": "Select Date & Time Slot",
    "cal_lbl_date": "Choose Day (September / October 2026)",
    "cal_lbl_time": "Available Slots in Lisbon (WEST)",
    "cal_lbl_loc": "Location / Studio",
    "opt_loc_chiado": "Chiado Boutique Studio (Private Room)",
    "opt_loc_saldanha": "Prescription Saldanha",
    "opt_loc_inhome": "In-Home (Lisbon & Cascais)",
    "opt_loc_online": "Online Video Coaching (Zoom)",
    "btn_confirm_booking": "Confirm & Schedule via Calendly →",
    "wa_view_title": "Direct Fast Message",
    "wa_view_sub": "Prefer to chat directly? Fill in your note and send via WhatsApp.",
    "btn_send_wa": "Open Direct WhatsApp Chat",
    "r2_badge": "5 Sessions Pack",
    "r3_badge": "10 Sessions Master",
    "r4_badge": "Duet (2 People)"
  },
  "de": {
    "announcement_text": "Jetzt buchbar: Herbst-Privatlektionen in Lissabon (Matwork, Reformer & Hausbesuche)",
    "nav_about": "Über mich",
    "nav_method": "Die Methode",
    "nav_services": "Lektionen",
    "nav_rates": "Preise",
    "nav_gallery": "Galerie",
    "nav_ecosystem": "Ökosystem",
    "nav_location": "Lissabon",
    "nav_quiz_btn": "Lektion Finden",
    "hero_eyebrow": "STOTT Pilates® Zertifiziert · Ehemalige Tänzerin",
    "hero_title_1": "Wo die Disziplin des Balletts",
    "hero_title_italic": "auf Klassisches & Reformer Pilates trifft.",
    "hero_lead": "Ausgebildet an der Hamburg Ballet Academy und ehemalige Profitänzerin in Berlin. Verbindung von reinem Matwork-Körpergewicht mit der dynamischen Federpräzision des Reformers in Lissabon.",
    "hero_cta_primary": "Private 1:1 Session Buchen",
    "hero_cta_secondary": "Die Methode Entdecken ↓",
    "cred_years": "Jahre Bühnen- & Bewegungsexzellenz",
    "cred_stott": "Goldstandard der Biomechanik",
    "cred_langs": "Fließende Sprachen (DE·EN·PT·IT)",
    "trust_title": "FUNDAMENTE DER EXZELLENZ",
    "hero_badge_title": "Studio & Hausbesuche in Lissabon",
    "hero_badge_sub": "Matwork · Reformer · Chiado · Saldanha",
    "hero_quote": "\"Bewegung ist nicht nur Training; es ist die architektonische Wiederherstellung deiner Wirbelsäulenausrichtung und Tiefenkraft.\"",
    "about_tag": "DIE KÜNSTLERIN HINTER DER METHODE",
    "about_title_1": "Von der deutschen Bühne",
    "about_title_2": "zur präzisesten Pilates-Praxis in Lissabon.",
    "about_p1": "Geboren in Mailand und geprägt durch die weltbekannte Hamburg Ballet Academy, tanzte Veronica jahrelang professionell in führenden Berliner Theater- und Contemporary-Produktionen (u.a. im Friedrichstadt-Palast).",
    "about_p2": "Nachdem sie erlebte, wie Pilates ihre eigene körperliche Langlebigkeit revolutionierte, absolvierte sie die anspruchsvolle STOTT Pilates® Zertifizierung. Heute verbindet sie in Lissabon die Anmut der klassischen Bühnenkunst mit moderner Sportbiomechanik.",
    "about_float_title": "Anatomie einer Tänzerin",
    "about_float_desc": "Jahre intensiver klassischer Ausbildung in Deutschland verleihen Veronica einen mikroskopischen Blick für Haltungsasymmetrien und Mikrokontraktionen.",
    "time_1_title": "Hamburg Ballet Academy",
    "time_1_desc": "Rigorose klassische Ausbildung, Raumintelligenz und biomechanische Meisterschaft.",
    "time_2_title": "Berliner Profibühne",
    "time_2_desc": "Bühnenperformance auf Spitzenniveau; tiefes Verständnis für Körperregeneration.",
    "time_3_title": "STOTT Pilates® & Lissabon Praxis",
    "time_3_desc": "Zertifiziertes Coaching auf Reha-Niveau, Einzeltraining & dynamische Gruppenformate.",
    "method_tag": "DIE KERNARCHITEKTUR",
    "method_title": "Matwork & Reformer: Das Komplette Spektrum",
    "method_subtitle": "Echtes Pilates vereint die reine Schwerkraftkontrolle der Matte mit dem variablen Federzug und der Wirbelsäulendekompression des Reformers.",
    "m1_title": "Mikroskopische Haltungsausrichtung",
    "m1_desc": "Erkennung und Korrektur von Becken- und Wirbelsäulenfehlstellungen, bevor sie zu chronischen Schmerzen werden.",
    "m1_tag": "Skelettgesundheit",
    "m2_title": "Matwork & Präzisions-Props",
    "m2_desc": "Beherrschung des Körpergewichts, Magic Circles und Bänder für eine tiefe Verbindung zum Core.",
    "m2_tag": "Core-Architektur",
    "m3_title": "Reformer-Federmechanik",
    "m3_desc": "Nutzung des Schlittenwiderstands zur Gelenkentlastung und zum gezielten Muskelaufbau.",
    "m3_tag": "Spannung & Fluss",
    "m4_title": "Mehrsprachige Herzlichkeit",
    "m4_desc": "Fließende Anweisungen auf Deutsch, Englisch, Portugiesisch oder Italienisch. Perfekt für Expats in Lissabon.",
    "m4_tag": "Expat-Freundlich",
    "sessions_tag": "MASSGESCHNEIDERTE FORMATE",
    "sessions_title": "Wähle deine Trainingsreise",
    "quiz_trigger_btn": "30-Sekunden-Quiz Starten",
    "badge_most_exclusive": "BELIEBTEST & INDIVIDUELL",
    "s1_sub": "Privatstudio / Hausbesuch / Online",
    "s1_title": "1-zu-1 Matwork & Reformer",
    "s1_desc": "Ein maßgeschneidertes 55-Minuten-Training, das Mattenübungen, Props und Reformer perfekt auf deinen Körper abstimmt.",
    "s1_f1": "Umfassende Haltungsanalyse zu Beginn",
    "s1_f2": "Hybrid aus Matte & vollem Reformer-Repertoire",
    "s1_f3": "Gezielte Linderung bei Rücken- und Nackenbeschwerden",
    "s1_f4": "Auf Deutsch, Englisch, Portugiesisch oder Italienisch",
    "btn_book_private": "1:1 Session Buchen",
    "s2_sub": "Halbprivat (2 Personen)",
    "s2_title": "Duett Pilates Erlebnis",
    "s2_desc": "Teile deine Trainingsstunde mit Partner oder Freundin. Genieße individuelle Korrekturen bei geteilten Kosten.",
    "s2_f1": "Synchronisierter Trainingsfortschritt",
    "s2_f2": "Persönliche Anpassung für beide",
    "s2_f3": "Ideal für Paare oder Freunde",
    "s2_f4": "Im Studio oder zu Hause verfügbar",
    "btn_book_duet": "Duett Anfragen",
    "s3_sub": "Prescription Lissabon Studios",
    "s3_title": "Signature Dynamic Reformer",
    "s3_desc": "Intensive, musikgetriebene Gruppen-Reformer-Sessions mit Fokus auf Ausdauer, Core-Kraft und Rhythmus.",
    "s3_f1": "Energiegeladene, kuratierte Playlists",
    "s3_f2": "Dynamischer Flow für Fortgeschrittene",
    "s3_f3": "In Saldanha, Alcântara und São Bento",
    "s3_f4": "Buchbar über ClassPass & Momence",
    "btn_view_schedule": "Studio-Stundenplan Ansehen",
    "price_from": "Ab",
    "price_per_sess": "/ Einheit",
    "price_per_pers": "/ Person",
    "price_studio_pack": "Studio-Paket",
    "price_per_class": "/ Klasse",
    "rates_tag": "INVESTITION IN DEINEN KÖRPER",
    "rates_title": "Transparente Preise & Pakete",
    "rates_subtitle": "Alle Einzellektionen beinhalten Haltungstracking, hygienische Premium-Ausstattung und individuelle Progression.",
    "th_format": "Format",
    "th_freq": "Frequenz",
    "th_langs": "Sprachen",
    "th_rate": "Preis",
    "th_action": "Aktion",
    "r1_title": "Einzelne Probe- & Haltungsanalyse",
    "r1_desc": "Ideal für Einsteiger zur Bewertung der Wirbelsäulenausrichtung und Zieldefinition (Matte oder Reformer).",
    "r1_freq": "Einzelne 60-Minuten-Session",
    "r1_langs": "DE · EN · PT · IT",
    "btn_book_trial": "Probestunde Buchen",
    "r2_title": "5er-Paket Privatlektionen 1:1",
    "r2_desc": "Intensiver Aufbau von Rumpfstabilität und Haltungskorrektur mit wöchentlichen Terminen.",
    "r2_freq": "5 x 55-Minuten Privattraining",
    "r2_langs": "DE · EN · PT · IT",
    "btn_select_pack": "Paket Wählen",
    "r3_title": "10er-Masterpaket Privat",
    "r3_desc": "Die nachhaltige skelettale und athletische Transformation inklusive individuellem Heimplans.",
    "r3_freq": "10 x 55-Minuten Privattraining",
    "r3_langs": "DE · EN · PT · IT",
    "r4_title": "Duett-Einheit (2 Personen)",
    "r4_desc": "Halbprivates Training für zwei Personen mit abgestimmtem Übungsprogramm.",
    "r4_freq": "Pro Person / Einheit",
    "r4_langs": "DE · EN · PT · IT",
    "btn_book_duet_row": "Duett Buchen",
    "gallery_tag": "VISUELLE ARCHITEKTUR & INSTAGRAM",
    "gallery_title": "Bewegung, Rhythmus & Präzision in Lissabon",
    "gallery_subtitle": "Einblicke in Veronicas Reformer-Sequenzen, Rumpfbiomechanik und Studioalltag.",
    "g1_tag": "Reformer Flow",
    "g1_title": "Dynamische Spannung & Gelenkausrichtung",
    "g2_tag": "Core-Architektur",
    "g2_title": "Tiefe Bauchmuskel- & Beckenpräzision",
    "g3_tag": "Matte & Wirbelsäule",
    "g3_title": "Segmentale Wirbelsäulenartikulation",
    "g4_tag": "Neuromuskulär",
    "g4_title": "Die Haltungskorrekturen der Tänzerin",
    "g5_tag": "Federdynamik",
    "g5_title": "Gelenkentlastung & kontrollierter Widerstand",
    "g6_tag": "Lissabon Praxis",
    "g6_title": "Energie, Rhythmus & kraftvoller Flow",
    "gallery_btn_text": "Veronica auf Instagram folgen @salaveronica",
    "eco_tag": "ÖKOSYSTEM & WOHLBEFINDEN",
    "eco_title": "Über das Einzeltraining Hinaus",
    "pod_badge": "Neuer Podcast",
    "pod_title": "The Mind & Movement Podcast",
    "pod_desc": "Zweiwöchentliche 15-minütige Episoden von Veronica über angewandte Biomechanik, Atmung und Regeneration.",
    "pod_ep": "Ep. 04: Warum Haltung deine tägliche Energie bestimmt (18 Min)",
    "pod_link": "Auf Spotify & Apple Hören →",
    "gear_badge": "Studio-Essentials",
    "gear_title": "Kuratierte Trainingsausrüstung",
    "gear_desc": "Veronicas ausgewählte Grip-Socken und rutschfeste Auflagen für maximale Sicherheit auf dem Reformer.",
    "gear_link": "Empfohlene Essentials Ansehen →",
    "priv_badge": "Partnerschaft & Fürsorge",
    "priv_title": "Vorteile für Künstler & Pflegeberufe",
    "priv_desc": "15% Nachlass auf Einzeltraining für aktive Tänzer, Bühnenkünstler und medizinisches Personal.",
    "priv_link": "Ermäßigung Anfragen →",
    "test_tag": "KUNDENSTIMMEN",
    "test_title": "Erfahrungen aus Lissabon & der Welt",
    "t1_text": "\"Als deutsche Expat in Lissabon eine zertifizierte STOTT-Trainerin zu finden, die Deutsch spricht und echten Tanzhintergrund hat, war ein Glücksfall. Meine Rückenschmerzen waren nach 6 Lektionen weg.\"",
    "t1_role": "Tech Executive & Expat, Lissabon",
    "t2_text": "\"Veronicas Anweisungen sind unvergleichlich. Man spürt sofort ihren Ballett-Hintergrund – jeder Millimeter wird korrigiert. Fordernd und zugleich von höchster Eleganz.\"",
    "t2_role": "Architektin, Chiado",
    "t3_text": "\"Ihre Energie auf dem Reformer bei Prescription ist legendär, aber das 1:1 Einzeltraining hat meine Regeneration auf ein neues Level gebracht. Weltklasse-Coaching.\"",
    "t3_role": "Triathlet, Cascais",
    "loc_tag": "TRAININGSORTE IN LISSABON",
    "loc_title_1": "Zentrales Lissabon",
    "loc_title_2": "Im Boutique-Studio oder bei dir zu Hause.",
    "loc_p": "Private 1:1 Sessions finden in ausgewählten Räumlichkeiten in Lissabon (Saldanha, Chiado, Santos) oder auf Wunsch bei dir zu Hause statt.",
    "loc_1_title": "Prescription Studios (Gruppe & Dynamisch)",
    "loc_1_desc": "Saldanha · Alcântara · São Bento · Parque das Nações",
    "loc_2_title": "Privatstudio 1-zu-1",
    "loc_2_desc": "Exklusiver Reformer-Raum mit vollständiger Privatsphäre.",
    "loc_3_title": "Hausbesuche / Cascais & Lissabon",
    "loc_3_desc": "Individuelles Matten- und Kleingerätetraining in deinen Räumen.",
    "map_title": "Lissabon Studio-Karte",
    "map_badge": "Jetzt Aktiv",
    "map_footer": "Direkte WhatsApp-Anfragen werden innerhalb von 2 Stunden beantwortet.",
    "contact_tag": "DIREKTER KONTAKT",
    "contact_title": "Starte deine Haltungstransformation",
    "contact_p": "Möchtest du die Präzision einer ehemaligen Profitänzerin erleben? Schreibe Veronica direkt für eine unverbindliche Terminkoordination.",
    "ch_1_title": "Schnellste Antwort via WhatsApp",
    "ch_1_desc": "Direkter Chat zur unkomplizierten Terminfindung.",
    "ch_2_title": "Gesprochene Sprachen",
    "ch_2_desc": "Deutsch, Englisch, Portugiesisch, Italienisch",
    "wa_btn_text": "Veronica auf WhatsApp Schreiben",
    "form_title": "Beratungstermin Vereinbaren",
    "form_subtitle": "Trage deine Wünsche ein und erhalte innerhalb von 24h freie Zeitfenster.",
    "lbl_name": "Dein Name",
    "lbl_email": "E-Mail-Adresse",
    "lbl_phone": "WhatsApp / Telefon",
    "lbl_interest": "Gewünschtes Format",
    "opt_private": "1-zu-1 Private Reformer Session",
    "opt_duet": "Duett Session (2 Personen)",
    "opt_trial": "Einführende Haltungsanalyse & Probestunde",
    "opt_studio": "Gruppenklassen bei Prescription",
    "lbl_lang_pref": "Bevorzugte Unterrichtssprache",
    "lbl_notes": "Ziele, Fragen oder Vorerkrankungen",
    "btn_submit_form": "Anfrage Absenden →",
    "modal_tag": "30-SEKUNDEN-QUIZ",
    "modal_title": "Finde deinen perfekten Pilates-Weg",
    "modal_subtitle": "Beantworte 2 kurze Fragen, um herauszufinden, welches Format am besten zu deinen Zielen passt.",
    "q1_title": "1. Was ist dein primäres Trainingsziel?",
    "q1_opt1": "Wirbelsäulengesundheit & Haltungsausrichtung",
    "q1_opt2": "Core-Kraft & athletisches Ganzkörpertraining",
    "q1_opt3": "Dynamische Energie & Rhythmus zur Musik",
    "q2_title": "2. Welche Erfahrung hast du mit dem Reformer?",
    "q2_opt1": "Kompletter Anfänger / Erstes Mal",
    "q2_opt2": "Etwas Matten- oder Reformer-Erfahrung",
    "q2_opt3": "Fortgeschritten / Ehemaliger Tänzer oder Athlet",
    "res_badge": "DEIN EMPFOHLENER WEG",
    "modal_btn": "Empfohlenen Termin Anfragen →",
    "footer_desc": "Hamburg Ballet Academy · Berliner Profibühne · STOTT Pilates® Zertifiziert. Private & Studio Praxis in Lissabon, Portugal.",
    "foot_nav_title": "Navigation",
    "foot_nav_about": "Über Veronica",
    "foot_nav_method": "Die Methode",
    "foot_nav_sessions": "Privat & Studio Formate",
    "foot_nav_rates": "Preise & Pakete",
    "foot_nav_eco": "Podcast & Essentials",
    "foot_loc_title": "Standorte & Studios",
    "foot_loc_sal": "Prescription Saldanha",
    "foot_loc_alc": "Prescription Alcântara",
    "foot_loc_chi": "Privatstudio Chiado",
    "foot_loc_cas": "Hausbesuche / Lissabon & Cascais",
    "foot_social_title": "Verbinden & Folgen",
    "foot_soc_wa": "WhatsApp Direkt",
    "foot_soc_ig": "Instagram @salaveronica",
    "foot_soc_fb": "Facebook",
    "foot_lang_note": "Unterricht fließend auf Deutsch, Englisch, Portugiesisch und Italienisch.",
    "foot_copy": "© 2026 Veronica Sala. Alle Rechte vorbehalten. Movement Architecture & STOTT Pilates.",
    "foot_crafted": "Präzise entwickelt für Veronica Sala",
    "r1_badge": "Empfohlen zum Einstieg",
    "eco_subtitle": "Von Audio-Wissen bis hin zu ausgewählten Trainings-Essentials.",
    "pod_track": "Audio-Vorschau anhören (1:30 Min)",
    "shop_badge": "Kuratierte Ausrüstung",
    "shop_title": "Studio Essentials & Grip Gear",
    "shop_desc": "Rutschfeste Grip-Socken und Reformer-Auflagen, ausgewählt von Veronica.",
    "shop_link": "Empfohlene Essentials Entdecken →",
    "tab_calendar": "Interaktiver Live-Kalender (Calendly)",
    "tab_whatsapp": "Schnellbuchung via WhatsApp",
    "ch_sync_title": "Sofortige Kalendersynchronisierung",
    "ch_sync_desc": "Automatische Einladung für Google / Apple Kalender mit Bestätigung.",
    "cal_badge_note": "Echtzeit-Verfügbarkeit: Chiado, Saldanha & Hausbesuch",
    "cal_default_badge": "Private 1:1 Matwork & Reformer Session",
    "cal_step1_title": "Datum & Zeitfenster Wählen",
    "cal_lbl_date": "Tag Wählen (September / Oktober 2026)",
    "cal_lbl_time": "Verfügbare Zeiten in Lissabon (WEST)",
    "cal_lbl_loc": "Standort / Studio",
    "opt_loc_chiado": "Chiado Boutique Studio (Privater Raum)",
    "opt_loc_saldanha": "Prescription Saldanha",
    "opt_loc_inhome": "Hausbesuch (Lissabon & Cascais)",
    "opt_loc_online": "Online Video Coaching (Zoom)",
    "btn_confirm_booking": "Termin auf Calendly Bestätigen →",
    "wa_view_title": "Direkte Schnellanfrage",
    "wa_view_sub": "Lieber direkt schreiben? Sende Veronica eine persönliche Nachricht auf WhatsApp.",
    "btn_send_wa": "Direkten WhatsApp-Chat Öffnen",
    "r2_badge": "5er-Paket",
    "r3_badge": "10er-Paket",
    "r4_badge": "Duett (2 Personen)"
  },
  "pt": {
    "announcement_text": "Inscrições abertas para sessões privadas de outono em Lisboa (Matwork, Reformer e ao Domicílio)",
    "nav_about": "Sobre",
    "nav_method": "O Método",
    "nav_services": "Sessões",
    "nav_rates": "Preçário",
    "nav_gallery": "Galeria",
    "nav_ecosystem": "Ecossistema",
    "nav_location": "Lisboa",
    "nav_quiz_btn": "Encontrar Sessão",
    "hero_eyebrow": "Certificada STOTT Pilates® · Ex-Bailarina Profissional",
    "hero_title_1": "Onde a Disciplina do Ballet",
    "hero_title_italic": "Encontra a Precisão do Reformer.",
    "hero_lead": "Formada na Hamburg Ballet Academy e ex-bailarina profissional em Berlim. Unindo o trabalho essencial de Matwork à precisão biomecânica do Reformer em Lisboa.",
    "hero_cta_primary": "Marcar Sessão Privada 1:1",
    "hero_cta_secondary": "Descobrir o Método ↓",
    "cred_years": "Anos de Mestria em Movimento",
    "cred_stott": "Padrão de Ouro em Biomecânica",
    "cred_langs": "Idiomas Fluentes (PT·EN·DE·IT)",
    "trust_title": "FUNDAMENTOS DE EXCELÊNCIA",
    "hero_badge_title": "Estúdio & Domicílio em Lisboa",
    "hero_badge_sub": "Matwork · Reformer · Chiado · Saldanha",
    "hero_quote": "\"O movimento não é apenas exercício; é a restauração arquitetónica do alinhamento esquelético, força profunda e consciência corporal.\"",
    "about_tag": "A ARTISTA POR DETRÁS DO MÉTODO",
    "about_title_1": "Dos Palcos Alemães",
    "about_title_2": "à Prática de Pilates mais Completa de Lisboa.",
    "about_p1": "Nascida em Milão e formada pela conceituada Hamburg Ballet Academy, Veronica atuou durante anos como bailarina profissional nas principais produções em Berlim (incluindo o prestigiado Friedrichstadt-Palast).",
    "about_p2": "Após descobrir como o Pilates revolucionou a sua longevidade física e prevenção de lesões, completou a certificação STOTT Pilates®—dominando o Matwork clássico e o Reformer com molas. Hoje em Lisboa, une a elegância da dança clássica à biomecânica desportiva.",
    "about_float_title": "A Anatomia de uma Bailarina",
    "about_float_desc": "Anos de treino clássico rigoroso na Alemanha dão a Veronica um olhar microscópico para assimetrias posturais e microcompensações no mat e no aparelho.",
    "time_1_title": "Hamburg Ballet Academy",
    "time_1_desc": "Base clássica rigorosa, inteligência espacial e mestria biomecânica.",
    "time_2_title": "Palco Profissional em Berlim",
    "time_2_desc": "Atuações ao mais alto nível; profundo conhecimento de longevidade corporal.",
    "time_3_title": "STOTT Pilates® & Prática em Lisboa",
    "time_3_desc": "Ensino de nível de reabilitação, coaching privado e aulas dinâmicas em estúdio.",
    "method_tag": "A ARQUITETURA ESSENCIAL",
    "method_title": "Matwork & Reformer: O Espetro Completo",
    "method_subtitle": "O verdadeiro Pilates combina o controlo gravitacional no tapete com a resistência e descompressão das molas do Reformer.",
    "m1_title": "Alinhamento Postural Microscópico",
    "m1_desc": "Deteção e correção precisa de desalinhamentos da bacia, coluna e pescoço antes de se tornarem dores crónicas.",
    "m1_tag": "Saúde Esquelética",
    "m2_title": "Matwork & Acessórios de Precisão",
    "m2_desc": "Domínio do peso corporal, Magic Circles e elásticos para uma conexão profunda com o core.",
    "m2_tag": "Arquitetura do Core",
    "m3_title": "Mecânica de Molas do Reformer",
    "m3_desc": "Utilização da resistência do carrinho para descompressão articular e fortalecimento progressivo.",
    "m3_tag": "Tensão & Fluidez",
    "m4_title": "Acolhimento Multilíngue",
    "m4_desc": "Instruções fluidas em Português, Inglês, Alemão ou Italiano. Ideal para residentes e expats em Lisboa.",
    "m4_tag": "Internacional",
    "sessions_tag": "FORMATOS PERSONALIZADOS",
    "sessions_title": "Escolhe a Tua Jornada de Movimento",
    "quiz_trigger_btn": "Fazer o Quiz de 30 Segundos",
    "badge_most_exclusive": "MAIS PROCURADO & EXCLUSIVO",
    "s1_sub": "Estúdio Privado / Domicílio / Online",
    "s1_title": "1-para-1 Matwork & Reformer",
    "s1_desc": "Sessão personalizada de 55 minutos combinando trabalho de solo, acessórios e Reformer adaptados à tua postura.",
    "s1_f1": "Avaliação Postural Inicial Completa",
    "s1_f2": "Repertório Híbrido Matwork e Reformer",
    "s1_f3": "Alívio Focado para Dores de Costas e Pescoço",
    "s1_f4": "Em Português, Inglês, Alemão ou Italiano",
    "btn_book_private": "Marcar Sessão 1:1",
    "s2_sub": "Semi-Privado (2 Pessoas)",
    "s2_title": "Experiência Pilates em Dueto",
    "s2_desc": "Partilha a tua aula com um parceiro ou amigo em mat ou reformer com atenção personalizada e custo partilhado.",
    "s2_f1": "Progressão de Movimento Sincronizada",
    "s2_f2": "Ajustes Personalizados para Ambos",
    "s2_f3": "Excelente para Casais ou Amigos",
    "s2_f4": "Disponível em Estúdio ou ao Domicílio",
    "btn_book_duet": "Pedir Informações Dueto",
    "s3_sub": "Estúdios Prescription Lisboa",
    "s3_title": "Signature Dynamic Reformer",
    "s3_desc": "Aulas de grupo de alta intensidade ao ritmo da música, focadas em resistência, força do core e fluidez.",
    "s3_f1": "Playlists Exclusivas com Alta Energia",
    "s3_f2": "Fluxo Dinâmico Intermédio e Avançado",
    "s3_f3": "Disponível em Saldanha, Alcântara e São Bento",
    "s3_f4": "Reservável no ClassPass & Momence",
    "btn_view_schedule": "Ver Horários de Estúdio",
    "price_from": "Desde",
    "price_per_sess": "/ sessão",
    "price_per_pers": "/ pessoa",
    "price_studio_pack": "Pack Estúdio",
    "price_per_class": "/ aula",
    "rates_tag": "INVESTIMENTO NO TEU CORPO",
    "rates_title": "Preçário Transparente & Packs",
    "rates_subtitle": "Todas as sessões privadas incluem monitorização postural, desinfeção de equipamento e progressão personalizada.",
    "th_format": "Formato",
    "th_freq": "Frequência",
    "th_langs": "Idiomas",
    "th_rate": "Valor",
    "th_action": "Ação",
    "r1_title": "Sessão Individual de Avaliação Postural",
    "r1_desc": "Ideal para primeira vez: avaliar alinhamento da coluna e definir metas (Mat ou Reformer).",
    "r1_freq": "Sessão individual de 60 min",
    "r1_langs": "PT · EN · DE · IT",
    "btn_book_trial": "Marcar Avaliação",
    "r2_title": "Pack 5 Sessões Privadas 1:1",
    "r2_desc": "Plano intensivo de correção postural e fortalecimento do core com horários semanais fixos.",
    "r2_freq": "5 sessões privadas de 55 min",
    "r2_langs": "PT · EN · DE · IT",
    "btn_select_pack": "Escolher Pack",
    "r3_title": "Pack Master 10 Sessões Privadas",
    "r3_desc": "Transformação esquelética e atlética completa com rotinas personalizadas para casa.",
    "r3_freq": "10 sessões privadas de 55 min",
    "r3_langs": "PT · EN · DE · IT",
    "r4_title": "Sessão em Dueto (2 Pessoas)",
    "r4_desc": "Sessão semiprivada para duas pessoas com programa coordenado.",
    "r4_freq": "Por pessoa / sessão",
    "r4_langs": "PT · EN · DE · IT",
    "btn_book_duet_row": "Marcar Dueto",
    "gallery_tag": "ARQUITETURA VISUAL & INSTAGRAM",
    "gallery_title": "Movimento, Ritmo & Precisão em Lisboa",
    "gallery_subtitle": "Imagens autênticas das sequências de Reformer, biomecânica e aulas de Veronica.",
    "g1_tag": "Fluxo Reformer",
    "g1_title": "Tensão Dinâmica & Alinhamento Articular",
    "g2_tag": "Arquitetura do Core",
    "g2_title": "Ativação Abdominal Profunda & Pélvica",
    "g3_tag": "Mat & Coluna",
    "g3_title": "Articulação Segmentar da Coluna",
    "g4_tag": "Neuromuscular",
    "g4_title": "Os Ajustes Posturais da Bailarina",
    "g5_tag": "Dinâmica de Molas",
    "g5_title": "Descompressão & Resistência Controlada",
    "g6_tag": "Prática em Lisboa",
    "g6_title": "Energia, Ritmo & Fluidez Empoderadora",
    "gallery_btn_text": "Seguir Veronica no Instagram @salaveronica",
    "eco_tag": "ECOSSISTEMA & BEM-ESTAR",
    "eco_title": "Para Além da Sessão Individual",
    "pod_badge": "Novo Podcast",
    "pod_title": "Podcast The Mind & Movement",
    "pod_desc": "Episódios quinzenais de 15 minutos de Veronica sobre biomecânica aplicada, respiração e prevenção de lesões.",
    "pod_ep": "Ep. 04: Porque a Postura Define a Tua Energia Diária (18 min)",
    "pod_link": "Ouvir no Spotify & Apple →",
    "gear_badge": "Essenciais de Estúdio",
    "gear_title": "Equipamento Curado para Estúdio",
    "gear_desc": "Meias aderentes e toalhas antideslizantes selecionadas por Veronica para máxima aderência no Reformer.",
    "gear_link": "Ver Essenciais Recomendados →",
    "priv_badge": "Parcerias & Cuidado",
    "priv_title": "Benefícios para Artistas e Saúde",
    "priv_desc": "Desconto de cortesia de 15% em sessões privadas para bailarinos profissionais, artistas e profissionais de saúde.",
    "priv_link": "Pedir Tarifa Especial →",
    "test_tag": "TESTEMUNHOS",
    "test_title": "A Voz de quem Treina em Lisboa",
    "t1_text": "\"Sendo uma expat em Lisboa, encontrar uma instrutora certificada STOTT que fala a minha língua e tem experiência real em dança foi fantástico. A minha dor lombar desapareceu em 6 sessões.\"",
    "t1_role": "Executiva Tech & Expat, Lisboa",
    "t2_text": "\"As correções verbais da Veronica são únicas. Sentes imediatamente a sua formação clássica de ballet. O trabalho muscular é intenso e a elegância impecável.\"",
    "t2_role": "Arquiteta, Chiado",
    "t3_text": "\"A energia dela no Reformer na Prescription é incrível, mas as sessões 1:1 elevaram a minha recuperação a outro nível. Coaching de nível mundial.\"",
    "t3_role": "Triatleta, Cascais",
    "loc_tag": "LOCAIS DE TREINO EM LISBOA",
    "loc_title_1": "Centro de Lisboa",
    "loc_title_2": "No Estúdio ou no Teu Domicílio.",
    "loc_p": "As sessões privadas 1:1 realizam-se em estúdios boutique em Lisboa (Saldanha, Chiado, Santos) ou ao domicílio com marcação prévia.",
    "loc_1_title": "Estúdios Prescription (Grupo & Dinâmico)",
    "loc_1_desc": "Saldanha · Alcântara · São Bento · Parque das Nações",
    "loc_2_title": "Estúdio Privado 1-para-1",
    "loc_2_desc": "Sala boutique reservada com Reformer com total privacidade.",
    "loc_3_title": "Ao Domicílio / Cascais & Lisboa",
    "loc_3_desc": "Aulas personalizadas de Matwork e pequenos equipamentos em tua casa.",
    "map_title": "Mapa de Estúdios em Lisboa",
    "map_badge": "Ativo Agora",
    "map_footer": "As mensagens diretas no WhatsApp são respondidas em 2 horas.",
    "contact_tag": "CONTACTO DIRETO",
    "contact_title": "Inicia a Tua Transformação Postural",
    "contact_p": "Queres experimentar a precisão de uma ex-bailarina profissional? Envia mensagem diretamente a Veronica para alinhar objetivos e verificar disponibilidade.",
    "ch_1_title": "Resposta Mais Rápida pelo WhatsApp",
    "ch_1_desc": "Chat direto para agendamento simples e rápido.",
    "ch_2_title": "Idiomas Falados",
    "ch_2_desc": "Português, Inglês, Alemão, Italiano",
    "wa_btn_text": "Mensagem para Veronica no WhatsApp",
    "form_title": "Agendar uma Avaliação",
    "form_subtitle": "Indica as tuas preferências e recebe horários disponíveis em 24h.",
    "lbl_name": "O Teu Nome",
    "lbl_email": "Endereço de Email",
    "lbl_phone": "WhatsApp / Telefone",
    "lbl_interest": "Formato de Sessão Preferido",
    "opt_private": "Sessão Privada 1-para-1 Matwork & Reformer",
    "opt_duet": "Sessão em Dueto (2 Pessoas)",
    "opt_trial": "Avaliação Postural Inicial e Experimental",
    "opt_studio": "Aulas de Grupo na Prescription",
    "lbl_lang_pref": "Idioma de Ensino Preferido",
    "lbl_notes": "Objetivos, Dúvidas ou Histórico de Lesões",
    "btn_submit_form": "Enviar Pedido de Contacto →",
    "modal_tag": "QUIZ DE 30 SEGUNDOS",
    "modal_title": "Descobre o Teu Caminho de Pilates Ideal",
    "modal_subtitle": "Responde a 2 perguntas rápidas para saberes qual o formato ideal para as tuas metas.",
    "q1_title": "1. Qual é o teu principal objetivo?",
    "q1_opt1": "Saúde da Coluna & Alinhamento Postural",
    "q1_opt2": "Força do Core & Condicionamento Atlético",
    "q1_opt3": "Energia Dinâmica & Ritmo com a Música",
    "q2_title": "2. Qual a tua experiência com aparelhos Reformer?",
    "q2_opt1": "Iniciante Absoluto / Primeira Vez",
    "q2_opt2": "Alguma experiência em Matwork ou Reformer",
    "q2_opt3": "Avançado / Ex-bailarino ou atleta",
    "res_badge": "O CAMINHO RECOMENDADO PARA TI",
    "modal_btn": "Avançar para Agendar Sessão →",
    "footer_desc": "Hamburg Ballet Academy · Palcos Profissionais de Berlim · Certificada STOTT Pilates®. Prática Privada e em Estúdio em Lisboa, Portugal.",
    "foot_nav_title": "Navegação",
    "foot_nav_about": "Sobre Veronica",
    "foot_nav_method": "O Método",
    "foot_nav_sessions": "Formatos Privados & Estúdio",
    "foot_nav_rates": "Preçário & Packs",
    "foot_nav_eco": "Podcast & Equipamento",
    "foot_loc_title": "Locais & Estúdios",
    "foot_loc_sal": "Prescription Saldanha",
    "foot_loc_alc": "Prescription Alcântara",
    "foot_loc_chi": "Estúdio Privado Chiado",
    "foot_loc_cas": "Ao Domicílio / Lisboa & Cascais",
    "foot_social_title": "Conectar & Seguir",
    "foot_soc_wa": "WhatsApp Direto",
    "foot_soc_ig": "Instagram @salaveronica",
    "foot_soc_fb": "Facebook",
    "foot_lang_note": "Aulas lecionadas fluentemente em Português, Inglês, Alemão e Italiano.",
    "foot_copy": "© 2026 Veronica Sala. Todos os direitos reservados. Movement Architecture & STOTT Pilates.",
    "foot_crafted": "Desenvolvido com precisão para Veronica Sala",
    "r1_badge": "Recomendado para Iniciar",
    "eco_subtitle": "Da partilha de conhecimento em áudio aos acessórios essenciais para a tua prática.",
    "pod_track": "Ouvir Pré-visualização de Áudio (1:30 min)",
    "shop_badge": "Equipamento Curado",
    "shop_title": "Studio Essentials & Grip Gear",
    "shop_desc": "Meias aderentes de alta tração e toalhas antiderrapantes selecionadas por Veronica.",
    "shop_link": "Explorar Acessórios Recomendados →",
    "tab_calendar": "Calendário Interativo (Calendly)",
    "tab_whatsapp": "Marcação Rápida WhatsApp",
    "ch_sync_title": "Sincronização de Calendário Imediata",
    "ch_sync_desc": "Convite direto enviado para o Google / Apple Calendar com lembrete.",
    "cal_badge_note": "Disponibilidade em Tempo Real: Chiado, Saldanha & Domicílio",
    "cal_default_badge": "Sessão Privada 1:1 Matwork & Reformer",
    "cal_step1_title": "Selecionar Data e Horário",
    "cal_lbl_date": "Escolhe o Dia (Setembro / Outubro 2026)",
    "cal_lbl_time": "Horários Disponíveis em Lisboa (WEST)",
    "cal_lbl_loc": "Localização / Estúdio",
    "opt_loc_chiado": "Estúdio Privado Chiado (Sala Reservada)",
    "opt_loc_saldanha": "Prescription Saldanha",
    "opt_loc_inhome": "Ao Domicílio (Lisboa & Cascais)",
    "opt_loc_online": "Vídeo Consulta Online (Zoom)",
    "btn_confirm_booking": "Confirmar & Agendar no Calendly →",
    "wa_view_title": "Mensagem Rápida Direta",
    "wa_view_sub": "Preferes falar diretamente? Envia a tua mensagem através do WhatsApp.",
    "btn_send_wa": "Abrir Conversa Direta no WhatsApp",
    "r2_badge": "Pack 5 Sessões",
    "r3_badge": "Pack 10 Sessões",
    "r4_badge": "Dueto (2 Pessoas)"
  }
};

let currentLang = 'en';
let selectedDay = 'Tue 22 Sep';
let selectedSlot = '11:30';
let selectedService = 'Private 1-on-1 Reformer Session';

// Detect browser language automatically
function initLanguage() {
  const browserLang = (navigator.language || navigator.userLanguage || 'en').toLowerCase();
  let defaultLang = 'en';
  if (browserLang.startsWith('it')) defaultLang = 'it';
  else if (browserLang.startsWith('de')) defaultLang = 'de';
  else if (browserLang.startsWith('pt')) defaultLang = 'pt';
  
  setLanguage(defaultLang);
}

function setLanguage(lang) {
  if (!i18n[lang]) return;
  currentLang = lang;
  
  // Update buttons state
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.getAttribute('data-lang') === lang);
  });

  // Translate all elements with data-i18n
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (i18n[lang] && i18n[lang][key]) {
      el.textContent = i18n[lang][key];
    }
  });

  // Sync Form language selector if present
  const langSelect = document.getElementById('langPreference');
  if (langSelect) langSelect.value = lang;
}

window.setLanguage = setLanguage;

// Tab Switcher (Calendly vs WhatsApp)
window.switchBookingTab = function(mode) {
  const tabCal = document.getElementById('tabCalendly');
  const tabWa = document.getElementById('tabWhatsapp');
  const viewCal = document.getElementById('calendlyView');
  const viewWa = document.getElementById('whatsappView');

  if (mode === 'calendly') {
    tabCal.classList.add('active');
    tabWa.classList.remove('active');
    viewCal.style.display = 'block';
    viewWa.style.display = 'none';
  } else {
    tabWa.classList.add('active');
    tabCal.classList.remove('active');
    viewWa.style.display = 'block';
    viewCal.style.display = 'none';
  }
};

// Calendar Selection Handlers
window.selectDay = function(btn, day) {
  selectedDay = day;
  document.querySelectorAll('.cal-day-btn').forEach(b => b.classList.remove('active'));
  btn.classList.add('active');
};

window.selectSlot = function(btn, slot) {
  selectedSlot = slot;
  document.querySelectorAll('.slot-chip').forEach(b => b.classList.remove('active'));
  btn.classList.add('active');
};

// Calendly Submission
window.handleCalendlySubmit = function() {
  const name = document.getElementById('calName').value;
  const email = document.getElementById('calEmail').value;
  const phone = document.getElementById('calPhone').value;
  const location = document.getElementById('calLocation').value;

  const box = document.getElementById('calConfirmBox');
  box.style.display = 'block';
  
  if (currentLang === 'it') {
    box.innerHTML = '<strong>Richiesta Registrata con Successo!</strong><br>Sessione: ' + selectedService + '<br>Data e Ora: ' + selectedDay + ' alle ' + selectedSlot + '<br>Sede: ' + location + '<br><em>Riceverai la conferma ufficiale e l\'invito per il calendario all\'indirizzo ' + email + '.</em>';
  } else if (currentLang === 'de') {
    box.innerHTML = '<strong>Terminanfrage Erfolgreich Erfasst!</strong><br>Lektion: ' + selectedService + '<br>Datum: ' + selectedDay + ' um ' + selectedSlot + ' Uhr<br>Ort: ' + location + '<br><em>Die Kalendereinladung wurde an ' + email + ' vorgemerkt.</em>';
  } else if (currentLang === 'pt') {
    box.innerHTML = '<strong>Marcação Registada com Sucesso!</strong><br>Sessão: ' + selectedService + '<br>Data: ' + selectedDay + ' às ' + selectedSlot + '<br>Local: ' + location + '<br><em>Receberás a confirmação no email ' + email + '.</em>';
  } else {
    box.innerHTML = '<strong>Appointment Requested Successfully!</strong><br>Session: ' + selectedService + '<br>Time: ' + selectedDay + ' at ' + selectedSlot + ' (WEST)<br>Location: ' + location + '<br><em>Calendar invite has been queued for ' + email + '.</em>';
  }

  // Also pre-fill WhatsApp message option
  const msg = encodeURIComponent('Hello Veronica! I just scheduled a ' + selectedService + ' on ' + selectedDay + ' at ' + selectedSlot + ' (' + location + ') for ' + name + ' (' + email + ', phone ' + phone + ').');
  setTimeout(() => {
    window.open('https://wa.me/351912345678?text=' + msg, '_blank');
  }, 1200);
};

// WhatsApp Direct
window.handleWhatsAppDirect = function() {
  const name = document.getElementById('waName').value;
  const service = document.getElementById('waService').value;
  const note = document.getElementById('waNote').value;

  const msg = encodeURIComponent('Hello Veronica! My name is ' + name + '. I am interested in: ' + service + '. Note: ' + note);
  window.open('https://wa.me/351912345678?text=' + msg, '_blank');
};

// Quiz Logic
let quizAnswers = { goal: '', exp: '' };

window.quizAnswer = function(type, val) {
  quizAnswers[type] = val;
  if (type === 'goal') {
    document.getElementById('qStep1').style.display = 'none';
    document.getElementById('qStep2').style.display = 'block';
  } else if (type === 'exp') {
    document.getElementById('qStep2').style.display = 'none';
    document.getElementById('qResult').style.display = 'block';
    calculateResult();
  }
};

function calculateResult() {
  const resTitle = document.getElementById('resTitle');
  const resDesc = document.getElementById('resDesc');
  const badge = document.getElementById('calServiceBadge');
  
  if (quizAnswers.goal === 'rehab' || quizAnswers.exp === 'beginner') {
    selectedService = (currentLang === 'it') ? "Sessione Privata 1:1 di Valutazione Posturale" : "Private 1-on-1 Assessment Session";
    if (currentLang === 'it') {
      resTitle.textContent = "Sessione Privata 1:1 di Valutazione Posturale";
      resDesc.textContent = "In base ai tuoi obiettivi, una sessione individuale su misura con Veronica ti darà la massima precisione nell'allineamento della colonna e nella protezione articolare.";
    } else if (currentLang === 'de') {
      resTitle.textContent = "Private 1:1 Haltungsanalyse & Reformer";
      resDesc.textContent = "Aufgrund deiner Ziele bietet dir eine maßgeschneiderte Einzelsession mit Veronica die präziseste Wirbelsäulen- und Gelenkentlastung.";
    } else if (currentLang === 'pt') {
      resTitle.textContent = "Sessão Privada 1:1 de Avaliação Postural";
      resDesc.textContent = "Com base nos teus objetivos, uma sessão individual com Veronica dará a máxima precisão no alinhamento da coluna e proteção articular.";
    } else {
      resTitle.textContent = "Private 1-on-1 Assessment Session";
      resDesc.textContent = "Based on your goals, a tailored 1:1 session with Veronica will give you the precise alignment cues and individual attention needed for maximal progress.";
    }
  } else {
    selectedService = (currentLang === 'it') ? "Percorso Dinamico Reformer & Core" : "Dynamic Reformer & Athletic Flow";
    if (currentLang === 'it') {
      resTitle.textContent = "Percorso Dinamico Reformer & Core";
      resDesc.textContent = "Ideale per potenziare resistenza e forza atletica con il controllo delle molle STOTT e la musicalità del metodo.";
    } else if (currentLang === 'de') {
      resTitle.textContent = "Dynamisches Reformer & Athletic Training";
      resDesc.textContent = "Perfekt für Athletik, Kraftausdauer und Core-Stabilität mit Musik und fließendem Tempo.";
    } else if (currentLang === 'pt') {
      resTitle.textContent = "Programa Dinâmico de Reformer & Core";
      resDesc.textContent = "Ideal para aumentar resistência e força atlética com o controlo de molas STOTT e ritmo envolvente.";
    } else {
      resTitle.textContent = "Dynamic Reformer & Athletic Flow";
      resDesc.textContent = "Perfect for conditioning, core strength, and spring dynamics with high-energy rhythm.";
    }
  }

  if (badge) badge.textContent = selectedService;
}

window.closeModal = function() {
  const modal = document.getElementById('quizModal');
  if (modal) modal.classList.remove('open');
  
  // Update badge and switch to calendly view
  const badge = document.getElementById('calServiceBadge');
  if (badge) badge.textContent = selectedService;
  window.switchBookingTab('calendly');
};

document.addEventListener('DOMContentLoaded', () => {
  initLanguage();

  const openBtn = document.getElementById('openQuizBtn');
  const closeBtn = document.getElementById('closeQuizBtn');
  const modal = document.getElementById('quizModal');

  if (openBtn && modal) {
    openBtn.addEventListener('click', () => {
      quizAnswers = { goal: '', exp: '' };
      document.getElementById('qStep1').style.display = 'block';
      document.getElementById('qStep2').style.display = 'none';
      document.getElementById('qResult').style.display = 'none';
      modal.classList.add('open');
    });
  }

  if (closeBtn && modal) {
    closeBtn.addEventListener('click', () => modal.classList.remove('open'));
  }
});
