/* ==========================================================================
   VERONICA SALA — PILATES & MOVEMENT ARCHITECTURE
   Application Logic & Multilingual Engine (EN / DE / PT / IT)
   ========================================================================== */

const i18n = {
  "en": {
    "announcement_text": "Now Booking Autumn Private Sessions in Lisbon (Matwork, Reformer & In-Home)",
    "nav_about": "About",
    "nav_method": "The Method",
    "nav_services": "Sessions",
    "nav_rates": "Rates",
    "nav_ecosystem": "Ecosystem",
    "nav_location": "Lisbon",
    "nav_quiz_btn": "Find Your Session",
    "hero_eyebrow": "STOTT Pilates® Certified · Former Dancer",
    "hero_title_1": "Where Ballet Discipline",
    "hero_title_italic": "Meets Classical & Reformer Pilates.",
    "hero_lead": "Trained at the Hamburg Ballet Academy and a former professional dancer in Berlin. Bridging the foundational power of Pilates Matwork with the dynamic precision of the Reformer machine in Lisbon.",
    "hero_cta_primary": "Book Private 1:1 Session",
    "hero_cta_secondary": "Discover The Method ↓",
    "cred_years": "Years Stage & Movement Mastery",
    "cred_stott": "Gold Standard Biomechanics",
    "cred_langs": "Fluent Languages (EN·DE·PT·IT)",
    "trust_title": "FOUNDATIONS OF EXCELLENCE",
    "hero_badge_title": "Lisbon Studio & In-Home",
    "hero_badge_sub": "Matwork · Reformer · Chiado · Saldanha",
    "hero_quote": "Movement is not just exercise; it is an architectural restoration of your skeletal alignment, core power, and body awareness.",
    "about_tag": "THE ARTIST BEHIND THE METHOD",
    "about_title_1": "From the German Stage",
    "about_title_2": "to Lisbon's Most Complete Pilates Practice.",
    "about_p1": "Born in Milan and shaped by the world-renowned Hamburg Ballet Academy, Veronica spent years performing as a professional dancer in Berlin's elite contemporary and theatre productions (including the prestigious Friedrichstadt-Palast).",
    "about_p2": "After discovering how Pilates revolutionized her own physical longevity and injury resilience, she completed the comprehensive STOTT Pilates® certification—mastering both classical floor Matwork with props and heavy spring-loaded Reformer apparatus. Today, as a lead trainer in Lisbon, she bridges the grace of classical stage artistry with contemporary sports science.",
    "about_float_title": "Anatomy of a Dancer",
    "about_float_desc": "Years of rigorous classical training in Germany give Veronica a microscopic eye for postural asymmetries and micro-compensation on both mat and machine.",
    "time_1_title": "Hamburg Ballet Academy",
    "time_1_desc": "Rigorous classical foundation, spatial intelligence & biomechanical mastery.",
    "time_2_title": "Berlin Professional Stage",
    "time_2_desc": "Performing at world-class levels; understanding body longevity and injury recovery.",
    "time_3_title": "STOTT Pilates® & Lisbon Practice",
    "time_3_desc": "Comprehensive Matwork, props, reformer coaching & dynamic group formats.",
    "method_tag": "THE CORE ARCHITECTURE",
    "method_title": "Matwork & Reformer: The Complete Spectrum",
    "method_subtitle": "True Pilates combines the pure gravitational control of floor Matwork with the spring resistance and spinal decompression of the Reformer.",
    "m1_title": "Microscopic Postural Alignment",
    "m1_desc": "Detecting and correcting pelvic tilts, spinal imbalances, and neck strain before they turn into chronic pain.",
    "m1_tag": "Skeletal Health",
    "m2_title": "Matwork & Precision Props",
    "m2_desc": "Mastering bodyweight gravity, Magic Circles, foam rollers, and resistance bands for pure core connection.",
    "m2_tag": "Core Architecture",
    "m3_title": "Reformer Spring Mechanics",
    "m3_desc": "Utilizing carriage resistance for joint decompression, lengthening, and progressive athletic loading.",
    "m3_tag": "Flow & Tension",
    "m4_title": "Multilingual Warmth",
    "m4_desc": "Seamless cues in English, German, Portuguese, or Italian. Perfect for Lisbon's international community.",
    "m4_tag": "Expat Friendly",
    "sessions_tag": "TAILORED FORMATS",
    "sessions_title": "Choose Your Movement Journey",
    "quiz_trigger_btn": "Take the 30-sec Match Quiz",
    "badge_most_exclusive": "MOST POPULAR & BESPOKE",
    "s1_sub": "Private Studio / In-Home / Online",
    "s1_title": "1-on-1 Matwork & Reformer",
    "s1_desc": "A completely customized 55-minute session combining floor matwork, precision props, and reformer apparatus tailored to your spine.",
    "s1_f1": "Comprehensive Initial Postural Assessment",
    "s1_f2": "Hybrid Matwork & Full Reformer Repertoire",
    "s1_f3": "Targeted Chronic Back/Neck Pain Relief",
    "s1_f4": "English, German, Portuguese or Italian",
    "btn_book_private": "Book 1:1 Session",
    "s2_sub": "Semi-Private (2 People)",
    "s2_title": "Duet Pilates Experience",
    "s2_desc": "Share your practice with a partner or friend on mat or reformer. Enjoy high-touch personal cues while sharing the energy and cost.",
    "s2_f1": "Synchronized Movement Progression",
    "s2_f2": "Personalized Adjustments for Both",
    "s2_f3": "Great for Couples or Friends",
    "s2_f4": "Available in Studio or In-Home",
    "btn_book_duet": "Inquire Duet",
    "s3_sub": "Prescription Lisbon Studios",
    "s3_title": "Signature Dynamic Reformer",
    "s3_desc": "High-intensity, music-driven group reformer sessions focusing on endurance, core strength and dynamic flow.",
    "s3_f1": "High-Energy Curated Playlists",
    "s3_f2": "Intermediate & Advanced Dynamic Flow",
    "s3_f3": "Available in Saldanha, Alcântara & São Bento",
    "s3_f4": "Bookable on ClassPass & Momence",
    "btn_view_schedule": "View Studio Schedule",
    "price_from": "From",
    "price_per_sess": "/ session",
    "price_per_pers": "/ person",
    "price_studio_pack": "Studio Pack",
    "price_per_class": "/ class",
    "rates_tag": "INVESTMENT IN YOUR BODY",
    "rates_title": "Transparent Rates & Value Packs",
    "rates_subtitle": "All private sessions include postural tracking, equipment sanitation, and bespoke progression.",
    "th_format": "Program Format",
    "th_freq": "Frequency",
    "th_langs": "Languages",
    "th_rate": "Rate",
    "th_action": "Action",
    "r1_title": "Single Trial & Posture Assessment",
    "r1_desc": "Ideal for first-timers to evaluate spinal alignment & establish goals (Mat or Reformer).",
    "r1_freq": "Single 60-min session",
    "r1_badge": "Intro Special",
    "btn_book_trial": "Book Trial",
    "r2_title": "5-Session Private Transformation Pack",
    "r2_desc": "Build consistent core engagement, spinal decompression and tone across mat & apparatus.",
    "r2_freq": "5 x 55-min sessions",
    "btn_select_pack": "Select Pack",
    "r3_title": "10-Session Master Practitioner Pack",
    "r3_desc": "Complete neuromuscular overhaul with priority weekly booking slots.",
    "r3_freq": "10 x 55-min sessions",
    "r4_title": "Duet 5-Pack (Two People)",
    "r4_desc": "Share private attention with partner or colleague on mat or reformer.",
    "r4_freq": "5 x 55-min sessions",
    "btn_book_duet_row": "Book Duet",
    "eco_tag": "THE EXTENDED ECOSYSTEM",
    "eco_title": "Beyond the Studio: Sound, Gear & Privileges",
    "eco_subtitle": "Inspired by Europe’s leading movement pioneers: audio masterclasses, curated equipment, and community privileges.",
    "pod_badge": "Apple Podcasts & Spotify",
    "pod_title": "The Mind & Movement Podcast",
    "pod_desc": "Conversations on dance physiology, matwork fundamentals, overcoming desk posture in Lisbon, and the science of the Reformer.",
    "pod_track": "Ep. 14: From Classical Ballet to Matwork & Reformer Biomechanics",
    "pod_link": "Listen on Apple & Spotify →",
    "shop_badge": "Curated by Veronica",
    "shop_title": "Studio Gear & Essentials",
    "shop_desc": "Organic cotton grip socks, non-slip reformer towels, Pilates magic circles, and resistance loops.",
    "shop_link": "Explore Favorite Brands →",
    "priv_badge": "Partnership & Care",
    "priv_title": "Artists & Healthcare Privileges",
    "priv_desc": "A dedicated 15% courtesy concession on private sessions for active dancers, theatre performers, and healthcare workers.",
    "priv_f1": "Verified Dancer Concession",
    "priv_f2": "Medical & Physio Referrals",
    "priv_link": "Apply for Concession Rate →",
    "test_tag": "CLIENT EXPERIENCES",
    "test_title": "Voices from Lisbon & Beyond",
    "t1_text": "As a German expat living in Lisbon, finding a certified STOTT trainer who speaks German and has genuine stage experience was a dream. Combining floor matwork with the reformer completely cured my desk posture.",
    "t1_author": "Elena M.",
    "t1_role": "Tech Executive & Expat, Lisbon",
    "t2_text": "Veronica’s cues are unlike any other instructor. You can immediately feel her classical ballet background—every centimeter of your posture is corrected. The burn is intense, but the elegance is unmatched.",
    "t2_author": "Sofia R.",
    "t2_role": "Architect, Chiado",
    "t3_text": "Her energy on the Reformer at Prescription is legendary, but the 1-on-1 private sessions at home took my athletic recovery to another dimension.",
    "t3_author": "Marco T.",
    "t3_role": "Triathlete, Cascais",
    "loc_tag": "WHERE TO PRACTICE IN LISBON",
    "loc_title_1": "Central Lisbon & Cascais",
    "loc_title_2": "In Studio, In-Home or Online.",
    "loc_p": "Private 1:1 sessions are held in boutique reformer spaces across Lisbon (Saldanha, Chiado, Santos) or directly at your private residence by appointment.",
    "loc_1_title": "Prescription Studios (Group & Dynamic)",
    "loc_1_desc": "Saldanha · Alcântara · São Bento · Parque das Nações",
    "loc_2_title": "Private Studio 1-on-1",
    "loc_2_desc": "Bespoke boutique reformer & mat space with complete privacy.",
    "loc_3_title": "In-Home / Cascais & Lisbon",
    "loc_3_desc": "Private matwork, props & mobile apparatus at your residence.",
    "map_title": "Lisbon Movement Map",
    "map_badge": "Active Now",
    "map_footer": "Direct WhatsApp booking responds within 2 hours.",
    "contact_tag": "DIRECT INQUIRIES",
    "contact_title": "Start Your Movement Transformation",
    "contact_p": "Ready to experience the precision of a former professional dancer? Send a message directly to Veronica to discuss your goals, check studio availability, or schedule an initial assessment.",
    "ch_1_title": "Fastest Response via WhatsApp",
    "ch_1_desc": "Direct mobile chat for quick schedule coordination.",
    "ch_2_title": "Languages Spoken",
    "ch_2_desc": "English, German (Deutsch), Portuguese (Português), Italian (Italiano)",
    "wa_btn_text": "Message Veronica on WhatsApp",
    "form_title": "Schedule a Consultation",
    "form_subtitle": "Fill in your preferences and receive available time slots within 24h.",
    "lbl_name": "Your Name",
    "lbl_email": "Email Address",
    "lbl_phone": "WhatsApp / Phone",
    "lbl_interest": "Preferred Session Format",
    "opt_private": "1-on-1 Private Pilates (Mat & Reformer)",
    "opt_duet": "Duet Session (2 people)",
    "opt_trial": "Introductory Assessment & Trial",
    "opt_studio": "Group Classes at Prescription",
    "lbl_lang_pref": "Preferred Instruction Language",
    "lbl_notes": "Goals, Inquiries or Medical History",
    "btn_submit_form": "Send Inquire Request →",
    "modal_tag": "30-SECOND MATCHER",
    "modal_title": "Find Your Perfect Pilates Pathway",
    "modal_subtitle": "Answer 2 quick questions to discover whether Private Mat & Reformer, Duet, or Studio is right for you.",
    "q1_title": "1. What is your primary movement goal?",
    "q1_opt1": "Spinal Health, Matwork & Postural Alignment",
    "q1_opt2": "Core Strength, Resistance & Athletic Conditioning",
    "q1_opt3": "Dynamic Energy & Rhythm with Music",
    "q2_title": "2. What is your preferred practice environment?",
    "q2_opt1": "Private 1-on-1 Studio or In-Home Matwork",
    "q2_opt2": "Duet with Friend or Partner",
    "q2_opt3": "High-Energy Reformer Studio Class",
    "res_badge": "YOUR RECOMMENDED PATH",
    "modal_btn": "Proceed to Book Recommended Session →",
    "footer_desc": "Hamburg Ballet Academy · Berlin Professional Stage · STOTT Pilates® Certified. Private Mat & Reformer Practice in Lisbon, Portugal.",
    "foot_nav_title": "Navigation",
    "foot_nav_about": "About Veronica",
    "foot_nav_method": "The Method",
    "foot_nav_sessions": "Private & Studio Formats",
    "foot_nav_rates": "Rates & Packs",
    "foot_nav_eco": "Podcast & Gear",
    "foot_loc_title": "Locations & Studios",
    "foot_loc_sal": "Prescription Saldanha",
    "foot_loc_alc": "Prescription Alcântara",
    "foot_loc_chi": "Private Studio Chiado",
    "foot_loc_cas": "In-Home Lisbon & Cascais",
    "foot_social_title": "Connect & Follow",
    "foot_soc_wa": "WhatsApp Direct",
    "foot_lang_note": "Classes taught fluently in English, Deutsch, Português & Italiano.",
    "foot_copy": "© 2026 Veronica Sala. All rights reserved. Movement Architecture & STOTT Pilates.",
    "foot_crafted": "Crafted with precision for Veronica Sala"
  },
  "de": {
    "announcement_text": "Jetzt buchbar: Private Pilates-Sessions in Lissabon (Matwork, Reformer & Zu Hause)",
    "nav_about": "Über Veronica",
    "nav_method": "Die Methode",
    "nav_services": "Sessions",
    "nav_rates": "Preise",
    "nav_ecosystem": "Ökosystem",
    "nav_location": "Lissabon",
    "nav_quiz_btn": "Finde Deine Session",
    "hero_eyebrow": "STOTT Pilates® Zertifiziert · Ehemalige Profi-Tänzerin",
    "hero_title_1": "Wo Ballett-Disziplin",
    "hero_title_italic": "auf Klassisches & Reformer Pilates trifft.",
    "hero_lead": "Ausgebildet an der Hamburgischen Ballettschule und ehemalige professionelle Tänzerin in Berlin. Die kraftvolle Basis des Matwork vereint mit der dynamischen Präzision des Reformers in Lissabon.",
    "hero_cta_primary": "Private 1:1 Session Buchen",
    "hero_cta_secondary": "Die Methode Entdecken ↓",
    "cred_years": "Jahre Bühnen- & Bewegungserfahrung",
    "cred_stott": "Goldstandard der Biomechanik",
    "cred_langs": "Fließende Sprachen (EN·DE·PT·IT)",
    "trust_title": "FUNDAMENTE DER EXZELLENZ",
    "hero_badge_title": "Lissabon Studio & Zu Hause",
    "hero_badge_sub": "Matwork · Reformer · Chiado · Saldanha",
    "hero_quote": "Bewegung ist nicht nur Training; es ist die architektonische Wiederherstellung Deiner Haltung, Rumpfkraft und Körperwahrnehmung.",
    "about_tag": "DIE KÜNSTLERIN HINTER DER METHODE",
    "about_title_1": "Von den deutschen Bühnen",
    "about_title_2": "zu Lissabons ganzheitlichster Pilates-Praxis.",
    "about_p1": "Geboren in Mailand und geprägt an der weltberühmten Hamburgischen Ballettschule, tanzte Veronica jahrelang auf den großen Bühnen Berlins (unter anderem am renommierten Friedrichstadt-Palast).",
    "about_p2": "Nachdem Pilates ihre eigene körperliche Langlebigkeit und Schmerzfreiheit revolutioniert hatte, absolvierte sie die umfassende STOTT Pilates® Zertifizierung – für klassisches Boden-Matwork mit Kleingeräten und Feder-Reformer. Heute verbindet sie in Lissabon die Grazie der Bühnenkunst mit moderner Sportwissenschaft.",
    "about_float_title": "Anatomie einer Tänzerin",
    "about_float_desc": "Jahrelanges klassisches Training in Deutschland verleiht Veronica einen mikroskopischen Blick für Fehlhaltungen auf der Matte wie am Gerät.",
    "time_1_title": "Hamburgische Ballettschule",
    "time_1_desc": "Klassische Meisterausbildung, Raumintelligenz & biomechanische Präzision.",
    "time_2_title": "Berliner Profibühne",
    "time_2_desc": "Höchstleistungen auf der Bühne; tiefes Verständnis für Körpergesundheit und Regeneration.",
    "time_3_title": "STOTT Pilates® & Lissabon Praxis",
    "time_3_desc": "Ganzheitliches Matwork, Kleingeräte, Reformer-Coaching & Studio-Klassen.",
    "method_tag": "DIE KERN-ARCHITEKTUR",
    "method_title": "Matwork & Reformer: Das Komplette Spektrum",
    "method_subtitle": "Wahres Pilates verbindet die reine Schwerkraftkontrolle des Boden-Matworks mit der Feder-Dekompression des Reformers.",
    "m1_title": "Mikroskopische Haltungskorrektur",
    "m1_desc": "Erkennen und Beheben von Beckenschiefständen und Nackenverspannungen, bevor sie zu chronischen Schmerzen werden.",
    "m1_tag": "Skelettale Gesundheit",
    "m2_title": "Matwork & Präzisions-Props",
    "m2_desc": "Körpergewichtskontrolle mit Pilates-Ring, Foam Roller und Bändern für tiefste Rumpfaktivierung.",
    "m2_tag": "Core-Architektur",
    "m3_title": "STOTT® Feder-Biomechanik",
    "m3_desc": "Gelenkschonende Dekompression und geführte Kraftentwicklung am Reformer-Schlitten.",
    "m3_tag": "Flow & Dynamik",
    "m4_title": "Mehrsprachige Begleitung",
    "m4_desc": "Anweisungen auf Deutsch, Englisch, Portugiesisch oder Italienisch. Perfekt für die internationale Community in Lissabon.",
    "m4_tag": "Expat-Freundlich",
    "sessions_tag": "MASSGESCHNEIDERTE FORMATE",
    "sessions_title": "Wähle Deinen persönlichen Weg",
    "quiz_trigger_btn": "Zum 30-Sekunden Match-Quiz",
    "badge_most_exclusive": "BELIEBTESTES FORMAT",
    "s1_sub": "Privates Studio / Zu Hause / Online",
    "s1_title": "1-zu-1 Matwork & Reformer",
    "s1_desc": "Eine 55-minütige, exakt auf Deine Wirbelsäule abgestimmte Kombination aus Boden-Matwork, Kleingeräten und Reformer.",
    "s1_f1": "Umfassende initiale Haltungsanalyse",
    "s1_f2": "Hybrides Matwork- & volles Reformer-Repertoire",
    "s1_f3": "Gezielte Linderung von Rücken- und Nackenschmerzen",
    "s1_f4": "Unterricht auf Deutsch, Englisch, Portugiesisch oder Italienisch",
    "btn_book_private": "1:1 Session Buchen",
    "s2_sub": "Halbprivat (2 Personen)",
    "s2_title": "Duett Pilates Training",
    "s2_desc": "Gemeinsam mit Partner oder Freund/in trainieren (Matte oder Reformer) – mit individueller Betreuung und geteilten Kosten.",
    "s2_f1": "Synchroner Bewegungsaufbau",
    "s2_f2": "Individuelle Korrekturen für beide Teilnehmende",
    "s2_f3": "Ideal für Paare oder Freund/innen",
    "s2_f4": "Verfügbar im Studio oder bei Dir zu Hause",
    "btn_book_duet": "Duett Anfragen",
    "s3_sub": "Prescription Lissabon Studios",
    "s3_title": "Signature Dynamic Reformer",
    "s3_desc": "Dynamische, musikgetriebene Gruppen-Reformer-Klassen für Ausdauer, Rumpfkraft und Flow.",
    "s3_f1": "Motivierende, kuratierte Musik-Playlists",
    "s3_f2": "Dynamischer Flow für Fortgeschrittene & Erfahrene",
    "s3_f3": "Verfügbar in Saldanha, Alcântara & São Bento",
    "s3_f4": "Buchbar über ClassPass & Momence",
    "btn_view_schedule": "Studio-Stundenplan Ansehen",
    "price_from": "Ab",
    "price_per_sess": "/ Session",
    "price_per_pers": "/ Person",
    "price_studio_pack": "Studio-Paket",
    "price_per_class": "/ Klasse",
    "rates_tag": "INVESTITION IN DEINEN KÖRPER",
    "rates_title": "Transparente Preise & Pakete",
    "rates_subtitle": "Alle privaten Sessions beinhalten Haltungsanalysen, Equipment-Hygiene und persönliche Trainingspläne.",
    "th_format": "Programm-Format",
    "th_freq": "Dauer",
    "th_langs": "Sprachen",
    "th_rate": "Preis",
    "th_action": "Aktion",
    "r1_title": "Einzelnes Probetraining & Haltungsanalyse",
    "r1_desc": "Ideal für Einsteiger zur Bewertung der Wirbelsäule und Festlegung der Ziele (Matte oder Reformer).",
    "r1_freq": "Einzelsitzung 60 Min.",
    "r1_badge": "Einführungspreis",
    "btn_book_trial": "Probetraining Buchen",
    "r2_title": "5er-Transformations-Paket (Privat)",
    "r2_desc": "Aufbau stabiler Rumpfmuskulatur, Wirbelsäulenentlastung und ganzheitliche Straffung.",
    "r2_freq": "5 x 55-Minuten Sessions",
    "btn_select_pack": "Paket Wählen",
    "r3_title": "10er-Master-Paket (Privat)",
    "r3_desc": "Komplette neuromuskuläre Neuausrichtung mit bevorzugter wöchentlicher Terminvergabe.",
    "r3_freq": "10 x 55-Minuten Sessions",
    "r4_title": "Duett 5er-Paket (Zwei Personen)",
    "r4_desc": "Exklusive Betreuung zu zweit (Matte oder Reformer) – perfekt für Partner oder Kolleg/innen.",
    "r4_freq": "5 x 55-Minuten Sessions",
    "btn_book_duet_row": "Duett Buchen",
    "eco_tag": "DAS ERWEITERTE ÖKOSYSTEM",
    "eco_title": "Über das Studio hinaus: Audio, Gear & Privilegien",
    "eco_subtitle": "Inspiriert von Europas führenden Pilates-Persönlichkeiten: Podcasts, ausgewähltes Equipment und Partner-Konditionen.",
    "pod_badge": "Apple Podcasts & Spotify",
    "pod_title": "The Mind & Movement Podcast",
    "pod_desc": "Gespräche über Tanzphysiologie, Matwork-Grundlagen, Haltung bei Büroarbeit in Lissabon und die Wissenschaft des Reformers.",
    "pod_track": "Ep. 14: Vom Bühnentanz zur Matwork- & Reformer-Biomechanik",
    "pod_link": "Auf Apple & Spotify Hören →",
    "shop_badge": "Kuriert von Veronica",
    "shop_title": "Studio Gear & Empfehlungen",
    "shop_desc": "Bio-Baumwoll Grip-Socken, rutschfeste Handtücher, Pilates-Ringe und Widerstandsbänder.",
    "shop_link": "Lieblingsmarken Entdecken →",
    "priv_badge": "Partnerschaft & Vorsorge",
    "priv_title": "Künstler & Gesundheitsberufe Privilegien",
    "priv_desc": "15% Ermäßigung auf private Sessions für aktive Tänzer/innen, Schauspieler und medizinisches Personal.",
    "priv_f1": "Verifizierter Tänzer-Nachlass",
    "priv_f2": "Medizin- & Physiotherapie-Referenzen",
    "priv_link": "Ermäßigung Anfragen →",
    "test_tag": "KUNDENSTIMMEN",
    "test_title": "Erfahrungen aus Lissabon & Europa",
    "t1_text": "Als deutsche Expat in Lissabon eine zertifizierte STOTT-Trainerin zu finden, die fließend Deutsch spricht und echte Bühnenerfahrung hat, war ein Traum. Die Kombination aus Matwork und Reformer hat meine Rückenschmerzen geheilt.",
    "t1_author": "Elena M.",
    "t1_role": "Tech Executive & Expat, Lissabon",
    "t2_text": "Veronicas Anweisungen sind unvergleichlich. Man spürt sofort ihren Ballett-Hintergrund – jeder Zentimeter der Haltung wird korrigiert. Intensiv, aber mit unvergleichlicher Eleganz.",
    "t2_author": "Sofia R.",
    "t2_role": "Architektin, Chiado",
    "t3_text": "Ihre Energie auf dem Reformer bei Prescription ist legendär, aber die privaten 1:1 Sessions zu Hause haben meine Regeneration auf ein neues Level gehoben.",
    "t3_author": "Marco T.",
    "t3_role": "Triathlet, Cascais",
    "loc_tag": "TRAININGSORTE IN LISSABON",
    "loc_title_1": "Zentral-Lissabon & Cascais",
    "loc_title_2": "Im Studio, zu Hause oder online.",
    "loc_p": "Private 1:1 Sessions finden in exklusiven Boutique-Räumen in Lissabon (Saldanha, Chiado, Santos) oder auf Wunsch bei Dir zu Hause statt.",
    "loc_1_title": "Prescription Studios (Gruppe & Dynamic)",
    "loc_1_desc": "Saldanha · Alcântara · São Bento · Parque das Nações",
    "loc_2_title": "Privatstudio 1-on-1",
    "loc_2_desc": "Exklusiver, voll ausgestatteter Reformer- & Matten-Raum mit absoluter Privatsphäre.",
    "loc_3_title": "Zu Hause / Cascais & Lissabon",
    "loc_3_desc": "Mobiles Matwork- & Kleingeräte-Training in Deiner Residenz.",
    "map_title": "Lissabon Trainingskarte",
    "map_badge": "Jetzt Verfügbar",
    "map_footer": "Direkte WhatsApp-Anfragen werden innerhalb von 2 Stunden beantwortet.",
    "contact_tag": "DIREKTER KONTAKT",
    "contact_title": "Beginne Deine Veränderung",
    "contact_p": "Erlebe die Präzision einer ehemaligen Profitänzerin. Schreibe Veronica direkt für Verfügbarkeiten oder ein Erstgespräch.",
    "ch_1_title": "Schnellste Antwort über WhatsApp",
    "ch_1_desc": "Direkter Chat zur unkomplizierten Terminabstimmung.",
    "ch_2_title": "Gesprochene Sprachen",
    "ch_2_desc": "Deutsch, Englisch, Portugiesisch, Italienisch",
    "wa_btn_text": "Veronica auf WhatsApp Schreiben",
    "form_title": "Beratung Anfragen",
    "form_subtitle": "Gib Deine Wünsche an und erhalte innerhalb von 24h Terminvorschläge.",
    "lbl_name": "Dein Name",
    "lbl_email": "E-Mail-Adresse",
    "lbl_phone": "WhatsApp / Telefon",
    "lbl_interest": "Gewünschtes Format",
    "opt_private": "1-on-1 Privates Pilates (Matte & Reformer)",
    "opt_duet": "Duett Session (2 Personen)",
    "opt_trial": "Erst-Assessment & Probetraining",
    "opt_studio": "Gruppenstunden bei Prescription",
    "lbl_lang_pref": "Bevorzugte Unterrichtssprache",
    "lbl_notes": "Ziele, Wünsche oder Vorerkrankungen",
    "btn_submit_form": "Anfrage Senden →",
    "modal_tag": "30-SEKUNDEN MATCHER",
    "modal_title": "Finde Dein Perfektes Pilates-Format",
    "modal_subtitle": "Beantworte 2 kurze Fragen und erfahre, ob 1:1 Matwork & Reformer, Duett oder Studio-Klassen am besten zu Dir passen.",
    "q1_title": "1. Was ist Dein primäres Trainingsziel?",
    "q1_opt1": "Rückengesundheit, Matwork & Haltungskorrektur",
    "q1_opt2": "Rumpfstärke, Widerstand & Athletik",
    "q1_opt3": "Dynamischer Flow mit Musik",
    "q2_title": "2. Welches Trainingsumfeld bevorzugst Du?",
    "q2_opt1": "1:1 Privatstudio oder Matwork zu Hause",
    "q2_opt2": "Duett mit Partner oder Freund/in",
    "q2_opt3": "Dynamische Reformer-Klasse im Studio",
    "res_badge": "DEINE EMPFOHLENE OPTION",
    "modal_btn": "Weiter zur Buchung der empfohlenen Session →",
    "footer_desc": "Hamburgische Ballettschule · Berliner Profibühne · STOTT Pilates® Zertifiziert. Private Matten- & Reformer-Praxis in Lissabon, Portugal.",
    "foot_nav_title": "Navigation",
    "foot_nav_about": "Über Veronica",
    "foot_nav_method": "Die Methode",
    "foot_nav_sessions": "Private & Studio-Formate",
    "foot_nav_rates": "Preise & Pakete",
    "foot_nav_eco": "Podcast & Gear",
    "foot_loc_title": "Standorte & Studios",
    "foot_loc_sal": "Prescription Saldanha",
    "foot_loc_alc": "Prescription Alcântara",
    "foot_loc_chi": "Privatstudio Chiado",
    "foot_loc_cas": "Zu Hause / Lissabon & Cascais",
    "foot_social_title": "Verbinden & Folgen",
    "foot_soc_wa": "Direkter WhatsApp-Kontakt",
    "foot_lang_note": "Unterricht fließend auf Deutsch, Englisch, Portugiesisch & Italienisch.",
    "foot_copy": "© 2026 Veronica Sala. Alle Rechte vorbehalten. Movement Architecture & STOTT Pilates.",
    "foot_crafted": "Mit Präzision für Veronica Sala entwickelt"
  },
  "pt": {
    "announcement_text": "Sessões Privadas em Lisboa Disponíveis (Matwork, Reformer e ao Domicílio)",
    "nav_about": "Sobre",
    "nav_method": "O Método",
    "nav_services": "Sessões",
    "nav_rates": "Preços",
    "nav_ecosystem": "Ecossistema",
    "nav_location": "Lisboa",
    "nav_quiz_btn": "Descobrir Sessão",
    "hero_eyebrow": "Certificada STOTT Pilates® · Ex-Bailarina Profissional",
    "hero_title_1": "Onde a Disciplina do Ballet",
    "hero_title_italic": "Encontra o Pilates Clássico & Reformer.",
    "hero_lead": "Formada na conceituada Hamburg Ballet Academy e ex-bailarina profissional em Berlim. Unindo a força fundacional do Pilates Matwork à precisão dinâmica do Reformer em Lisboa.",
    "hero_cta_primary": "Marcar Sessão Privada 1:1",
    "hero_cta_secondary": "Conhecer o Método ↓",
    "cred_years": "Anos de Maestria de Movimento",
    "cred_stott": "Padrão de Ouro em Biomecânica",
    "cred_langs": "Idiomas Fluentes (EN·DE·PT·IT)",
    "trust_title": "PILAREM DE EXCELÊNCIA",
    "hero_badge_title": "Estúdio em Lisboa & Ao Domicílio",
    "hero_badge_sub": "Matwork · Reformer · Chiado · Saldanha",
    "hero_quote": "O movimento não é apenas exercício; é a restauração arquitetónica do seu alinhamento, força do core e consciência corporal.",
    "about_tag": "A ARTISTA POR TRÁS DO MÉTODO",
    "about_title_1": "Dos Palcos Alemães",
    "about_title_2": "à Prática de Pilates Mais Completa de Lisboa.",
    "about_p1": "Nascida em Milão e formada na prestigiada Hamburg Ballet Academy, Veronica atuou como bailarina profissional em Berlim em produções de topo (incluindo o conceituado Friedrichstadt-Palast).",
    "about_p2": "Após comprovar como o Pilates transformou a sua própria longevidade física, concluiu a rigorosa certificação STOTT Pilates® — dominando tanto o Matwork de solo com pequenos acessórios como o trabalho em máquinas Reformer. Hoje, em Lisboa, une a elegância da dança à ciência desportiva contemporânea.",
    "about_float_title": "Anatomia de Bailarina",
    "about_float_desc": "Anos de treino clássico na Alemanha dão a Veronica um olhar milimétrico para compensações posturais tanto no colchão como no equipamento.",
    "time_1_title": "Hamburg Ballet Academy",
    "time_1_desc": "Formação clássica de topo, inteligência espacial e mestria biomecânica.",
    "time_2_title": "Palcos Profissionais em Berlim",
    "time_2_desc": "Performances ao mais alto nível; profundo conhecimento sobre longevidade articular e recuperação.",
    "time_3_title": "STOTT Pilates® & Prática em Lisboa",
    "time_3_desc": "Matwork completo, acessórios, coaching de reformer e aulas de grupo.",
    "method_tag": "ARQUITETURA DO MOVIMENTO",
    "method_title": "Matwork & Reformer: O Espectro Completo",
    "method_subtitle": "O verdadeiro Pilates une o controlo postural da gravidade no solo à descompressão e resistência por molas do Reformer.",
    "m1_title": "Alinhamento Postural Microscópico",
    "m1_desc": "Deteção e correção de desvios pélvicos e tensões cervicais antes que se tornem dores crónicas.",
    "m1_tag": "Saúde Esquelética",
    "m2_title": "Matwork & Acessórios de Precisão",
    "m2_desc": "Controlo corporal puro com Magic Circle, foam roller e elásticos para ativação profunda do core.",
    "m2_tag": "Arquitetura do Core",
    "m3_title": "Mecânica das Molas STOTT®",
    "m3_desc": "Descompressão articular e fortalecimento muscular progressivo no carrinho do Reformer.",
    "m3_tag": "Tensão & Fluidez",
    "m4_title": "Acompanhamento Multilíngue",
    "m4_desc": "Instruções claras em Português, Inglês, Alemão ou Italiano. Ideal para a comunidade internacional.",
    "m4_tag": "Expat-Friendly",
    "sessions_tag": "FORMATOS PERSONALIZADOS",
    "sessions_title": "Escolha a Sua Jornada",
    "quiz_trigger_btn": "Fazer o Quiz de 30 Segundos",
    "badge_most_exclusive": "MAIS EXCLUSIVO",
    "s1_sub": "Estúdio Privado / Ao Domicílio / Online",
    "s1_title": "1-para-1 Matwork & Reformer",
    "s1_desc": "Sessão personalizada de 55 minutos combinando exercícios de solo, acessórios e aparelho Reformer à medida da sua coluna.",
    "s1_f1": "Avaliação Postural Inicial Completa",
    "s1_f2": "Repertório Híbrido de Matwork e Reformer",
    "s1_f3": "Alívio Específico de Dores Lombares e Cervicais",
    "s1_f4": "Instrução em Português, Inglês, Alemão ou Italiano",
    "btn_book_private": "Marcar Sessão 1:1",
    "s2_sub": "Semiprivado (2 Pessoas)",
    "s2_title": "Experiência Duet Pilates",
    "s2_desc": "Treine com um parceiro ou amiga (no solo ou no reformer) com atenção individualizada e custos partilhados.",
    "s2_f1": "Progressão de Movimento Sincronizada",
    "s2_f2": "Ajustes Personalizados para Ambos",
    "s2_f3": "Excelente para Casais ou Amigos",
    "s2_f4": "Disponível em Estúdio ou ao Domicílio",
    "btn_book_duet": "Pedir Informação Duet",
    "s3_sub": "Estúdios Prescription Lisboa",
    "s3_title": "Signature Dynamic Reformer",
    "s3_desc": "Aulas de grupo dinâmicas ao ritmo da música para força e resistência de corpo inteiro.",
    "s3_f1": "Playlists Exclusivas com Energia Contagiante",
    "s3_f2": "Fluxo Dinâmico Intermédio e Avançado",
    "s3_f3": "Disponível em Saldanha, Alcântara e São Bento",
    "s3_f4": "Reserva via ClassPass e Momence",
    "btn_view_schedule": "Ver Horários de Estúdio",
    "price_from": "Desde",
    "price_per_sess": "/ sessão",
    "price_per_pers": "/ pessoa",
    "price_studio_pack": "Pack Estúdio",
    "price_per_class": "/ aula",
    "rates_tag": "INVESTIMENTO NO SEU CORPO",
    "rates_title": "Tabela de Preços e Pacotes",
    "rates_subtitle": "Todas as sessões privadas incluem avaliação postural, higiene do equipamento e planos progressivos.",
    "th_format": "Formato de Programa",
    "th_freq": "Duração",
    "th_langs": "Idiomas",
    "th_rate": "Valor",
    "th_action": "Ação",
    "r1_title": "Avaliação Inicial & Aula Experimental",
    "r1_desc": "Ideal para quem começa: avaliação da coluna vertebral e definição de objetivos (Solo ou Reformer).",
    "r1_freq": "Sessão individual 60 min",
    "r1_badge": "Preço de Lançamento",
    "btn_book_trial": "Marcar Prova",
    "r2_title": "Pack Transformação 5 Sessões (Privado)",
    "r2_desc": "Desenvolvimento do core, descompressão da coluna e tonificação completa (Mat & Reformer).",
    "r2_freq": "5 sessões de 55 min",
    "btn_select_pack": "Selecionar Pack",
    "r3_title": "Pack Master 10 Sessões (Privado)",
    "r3_desc": "Transformação neuromuscular completa com prioridade na escolha de horários semanais.",
    "r3_freq": "10 sessões de 55 min",
    "r4_title": "Pack Duet 5 Sessões (Duas Pessoas)",
    "r4_desc": "Atenção personalizada a dois (no solo ou no reformer) – ideal para casais ou colegas.",
    "r4_freq": "5 sessões de 55 min",
    "btn_book_duet_row": "Marcar Duet",
    "eco_tag": "ECOSSISTEMA ESTENDIDO",
    "eco_title": "Além do Estúdio: Podcast, Equipamento & Parcerias",
    "eco_subtitle": "Inspirado nas maiores referências europeias: masterclasses em áudio, acessórios selecionados e benefícios para a comunidade.",
    "pod_badge": "Apple Podcasts & Spotify",
    "pod_title": "The Mind & Movement Podcast",
    "pod_desc": "Episódios sobre fisiologia da dança, fundamentos de Matwork, postura de secretária em Lisboa e ciência do Reformer.",
    "pod_track": "Ep. 14: Do Ballet Clássico à Biomecânica de Matwork & Reformer",
    "pod_link": "Ouvir no Apple & Spotify →",
    "shop_badge": "Seleção por Veronica",
    "shop_title": "Equipamento & Essenciais",
    "shop_desc": "Meias antiderrapantes de algodão orgânico, toalhas especiais para reformer, anéis de Pilates e bandas elásticas.",
    "shop_link": "Ver Marcas Recomendadas →",
    "priv_badge": "Parcerias & Saúde",
    "priv_title": "Benefícios para Artistas e Saúde",
    "priv_desc": "Desconto de cortesia de 15% em sessões privadas para bailarinos profissionais e profissionais de saúde.",
    "priv_f1": "Desconto Verificado para Bailarinos",
    "priv_f2": "Recomendações Médicas e de Fisioterapia",
    "priv_link": "Pedir Desconto Especial →",
    "test_tag": "TESTEMUNHOS",
    "test_title": "Experiências em Lisboa",
    "t1_text": "Como expat alemã em Lisboa, encontrar uma instrutora STOTT que fale alemão e tenha experiência real de palco foi incrível. A combinação de exercícios de solo com o reformer curou as minhas dores nas costas.",
    "t1_author": "Elena M.",
    "t1_role": "Executiva Tech & Expat, Lisboa",
    "t2_text": "As correções da Veronica são únicas. Sente-se imediatamente a sua formação em ballet clássico — cada centímetro da postura é alinhado. Intenso, mas com uma elegância inigualável.",
    "t2_author": "Sofia R.",
    "t2_role": "Arquiteta, Chiado",
    "t3_text": "A energia dela no Reformer da Prescription é fantástica, mas as sessões privadas 1-para-1 em casa levaram a minha recuperação desportiva para outro nível.",
    "t3_author": "Marco T.",
    "t3_role": "Triatleta, Cascais",
    "loc_tag": "LOCAIS DE TREINO EM LISBOA",
    "loc_title_1": "Centro de Lisboa & Cascais",
    "loc_title_2": "No estúdio, ao domicílio ou online.",
    "loc_p": "Sessões privadas realizadas em estúdios boutique em Lisboa (Saldanha, Chiado, Santos) ou ao domicílio mediante marcação.",
    "loc_1_title": "Estúdios Prescription (Grupo & Dinâmico)",
    "loc_1_desc": "Saldanha · Alcântara · São Bento · Parque das Nações",
    "loc_2_title": "Estúdio Privado 1-para-1",
    "loc_2_desc": "Espaço boutique exclusivo de solo e reformer com privacidade total.",
    "loc_3_title": "Ao Domicílio / Cascais & Lisboa",
    "loc_3_desc": "Aulas personalizadas de solo e acessórios na sua residência.",
    "map_title": "Mapa de Estúdios em Lisboa",
    "map_badge": "Disponível Agora",
    "map_footer": "Mensagens diretas no WhatsApp com resposta em 2 horas.",
    "contact_tag": "CONTACTO DIRETO",
    "contact_title": "Inicie a Sua Transformação",
    "contact_p": "Envie uma mensagem diretamente a Veronica para falar sobre os seus objetivos e marcar a primeira avaliação.",
    "ch_1_title": "Resposta Mais Rápida por WhatsApp",
    "ch_1_desc": "Contacto direto e ágil para coordenação de horários.",
    "ch_2_title": "Idiomas Falados",
    "ch_2_desc": "Português, Inglês, Alemão, Italiano",
    "wa_btn_text": "Enviar Mensagem no WhatsApp",
    "form_title": "Pedir Informações",
    "form_subtitle": "Preencha as suas preferências para receber horários disponíveis em 24h.",
    "lbl_name": "O Seu Nome",
    "lbl_email": "Endereço de Email",
    "lbl_phone": "WhatsApp / Telefone",
    "lbl_interest": "Formato de Sessão Preferido",
    "opt_private": "1-para-1 Pilates Privado (Solo & Reformer)",
    "opt_duet": "Sessão Duet (2 pessoas)",
    "opt_trial": "Avaliação Inicial & Aula Experimental",
    "opt_studio": "Aulas de Grupo na Prescription",
    "lbl_lang_pref": "Idioma de Instrução Preferido",
    "lbl_notes": "Objetivos ou Histórico de Saúde",
    "btn_submit_form": "Enviar Pedido de Contacto →",
    "modal_tag": "30-SEGUNDOS MATCHER",
    "modal_title": "Encontre a Sua Sessão Ideal",
    "modal_subtitle": "Responda a 2 perguntas rápidas para descobrir se a opção Privada Mat & Reformer, Duet ou Estúdio é a melhor para si.",
    "q1_title": "1. Qual é o seu objetivo principal?",
    "q1_opt1": "Saúde da Coluna, Matwork & Alinhamento",
    "q1_opt2": "Fortalecimento do Core, Resistência & Treino Atlético",
    "q1_opt3": "Energia Dinâmica & Ritmo com Música",
    "q2_title": "2. Qual é o seu ambiente de treino preferido?",
    "q2_opt1": "Estúdio Privado 1:1 ou Matwork ao Domicílio",
    "q2_opt2": "Duet com Parceiro ou Amiga",
    "q2_opt3": "Aula de Grupo Dinâmica em Estúdio",
    "res_badge": "A SUA OPÇÃO RECOMENDADA",
    "modal_btn": "Avançar para Marcar Sessão Recomendada →",
    "footer_desc": "Hamburg Ballet Academy · Palcos Profissionais em Berlim · Certificada STOTT Pilates®. Prática Privada de Solo e Reformer em Lisboa, Portugal.",
    "foot_nav_title": "Navegação",
    "foot_nav_about": "Sobre Veronica",
    "foot_nav_method": "O Método",
    "foot_nav_sessions": "Formatos Privados & Estúdio",
    "foot_nav_rates": "Preços & Packs",
    "foot_nav_eco": "Podcast & Equipamento",
    "foot_loc_title": "Locais & Estúdios",
    "foot_loc_sal": "Prescription Saldanha",
    "foot_loc_alc": "Prescription Alcântara",
    "foot_loc_chi": "Estúdio Privado Chiado",
    "foot_loc_cas": "Ao Domicílio / Lisboa & Cascais",
    "foot_social_title": "Ligar & Seguir",
    "foot_soc_wa": "WhatsApp Direto",
    "foot_lang_note": "Aulas ministradas fluentemente em Português, Inglês, Alemão e Italiano.",
    "foot_copy": "© 2026 Veronica Sala. Todos os direitos reservados. Movement Architecture & STOTT Pilates.",
    "foot_crafted": "Desenvolvido com precisão para Veronica Sala"
  },
  "it": {
    "announcement_text": "Sessioni Private a Lisbona Disponibili (Matwork, Reformer & A Domicilio)",
    "nav_about": "Chi Sono",
    "nav_method": "Il Metodo",
    "nav_services": "Sessioni",
    "nav_rates": "Listino",
    "nav_ecosystem": "Ecosistema",
    "nav_location": "Lisbona",
    "nav_quiz_btn": "Trova il Tuo Percorso",
    "hero_eyebrow": "Certificata STOTT Pilates® · Ex Ballerina Professionista",
    "hero_title_1": "Dove la Disciplina della Danza",
    "hero_title_italic": "Incontra il Pilates Classico & Reformer.",
    "hero_lead": "Formata alla prestigiosa Hamburg Ballet Academy ed ex ballerina professionista a Berlino. Unisce la forza fondamentale del Pilates Matwork a corpo libero con la precisione dinamica dei macchinari Reformer a Lisbona.",
    "hero_cta_primary": "Prenota Sessione Privata 1:1",
    "hero_cta_secondary": "Scopri il Metodo ↓",
    "cred_years": "Anni di Palcoscenico e Movimento",
    "cred_stott": "Gold Standard Internazionale STOTT®",
    "cred_langs": "Lingue Fluite (IT·DE·EN·PT)",
    "trust_title": "FONDAZIONI DI ECCELLENZA",
    "hero_badge_title": "Studio a Lisbona & A Domicilio",
    "hero_badge_sub": "Matwork · Reformer · Chiado · Saldanha",
    "hero_quote": "Il movimento non è solo esercizio; è il restauro architettonico del tuo allineamento scheletrico, della forza del core e della consapevolezza corporea.",
    "about_tag": "L'ARTISTA DIETRO IL METODO",
    "about_title_1": "Dai Palcoscenici Tedeschi",
    "about_title_2": "alla Pratica di Pilates Più Completa di Lisbona.",
    "about_p1": "Nata a Milano e forgiata dalla celebre Hamburg Ballet Academy, Veronica ha lavorato come ballerina professionista a Berlino nelle più prestigiose produzioni contemporanee e teatrali (tra cui il celebre Friedrichstadt-Palast).",
    "about_p2": "Dopo aver sperimentato come il Pilates abbia salvaguardato e potenziato il suo corpo, ha conseguito la rigorosa certificazione STOTT Pilates® — padroneggiando sia il Matwork classico a terra con piccoli attrezzi, sia il lavoro su macchinari Reformer a molle. Oggi a Lisbona unisce la grazia e la disciplina del palcoscenico alla scienza biomeccanica.",
    "about_float_title": "Anatomia di una Ballerina",
    "about_float_desc": "Anni di danza classica d'alta scuola danno a Veronica un occhio millimetrico per correggere asimmetrie e compensazioni posturali sia sul tappetino che sui macchinari.",
    "time_1_title": "Hamburg Ballet Academy",
    "time_1_desc": "Formazione classica d'eccellenza, intelligenza spaziale e maestria biomeccanica.",
    "time_2_title": "Palcoscenici di Berlino",
    "time_2_desc": "Spettacoli ai massimi livelli europei; profonda comprensione della longevità e del recupero corporeo.",
    "time_3_title": "STOTT Pilates® & Pratica a Lisbona",
    "time_3_desc": "Matwork completo, piccoli attrezzi, coaching su Reformer e classi in studio.",
    "method_tag": "L'ARCHITETTURA DEL CORPO",
    "method_title": "Matwork & Reformer: Lo Spettro Completo",
    "method_subtitle": "Il vero Pilates unisce il controllo posturale a corpo libero contro gravità alla decompressione e resistenza guidata delle molle del Reformer.",
    "m1_title": "Allineamento Posturale Millimetrico",
    "m1_desc": "Individuazione e correzione di disallineamenti del bacino e tensioni cervicali prima che diventino dolori cronici.",
    "m1_tag": "Salute Scheletrica",
    "m2_title": "Matwork & Attrezzi di Precisione",
    "m2_desc": "Controllo a corpo libero con Magic Circle, foam roller e bande elastiche per una connessione profonda del core.",
    "m2_tag": "Architettura Core",
    "m3_title": "Biomeccanica a Molle STOTT®",
    "m3_desc": "Decompressione articolare, allungamento attivo e potenziamento progressivo sul carrello del Reformer.",
    "m3_tag": "Tensione & Flusso",
    "m4_title": "Guida Multilingua",
    "m4_desc": "Indicazioni perfette in Italiano, Tedesco, Inglese e Portoghese. Ideale per la community internazionale.",
    "m4_tag": "Adatto a Expat",
    "sessions_tag": "PERCORSI SU MISURA",
    "sessions_title": "Scegli la Tua Esperienza di Movimento",
    "quiz_trigger_btn": "Fai il Quiz da 30 Secondi",
    "badge_most_exclusive": "IL PIÙ RICHIESTO",
    "s1_sub": "Studio Privato / A Domicilio / Online",
    "s1_title": "1-a-1 Matwork & Reformer",
    "s1_desc": "Una sessione personalizzata di 55 minuti che unisce esercizi a terra, piccoli attrezzi e Reformer su misura per la tua colonna.",
    "s1_f1": "Valutazione Posturale Iniziale Approfondita",
    "s1_f2": "Repertorio Ibrido di Matwork e Reformer Completo",
    "s1_f3": "Sollievo Mirato per Dolori a Schiena e Cervicale",
    "s1_f4": "Istruzione in Italiano, Tedesco, Inglese o Portoghese",
    "btn_book_private": "Prenota Sessione 1:1",
    "s2_sub": "Semiprivato (2 Persone)",
    "s2_title": "Esperienza Duet Pilates",
    "s2_desc": "Condividi la pratica con un partner o un'amica (a terra o su reformer) con correzioni personalizzate e costi divisi.",
    "s2_f1": "Progressione di Movimento Sincronizzata",
    "s2_f2": "Correzioni su Misura per Entrambi",
    "s2_f3": "Ideale per Coppie o Amici",
    "s2_f4": "Disponibile in Studio o a Domicilio",
    "btn_book_duet": "Richiedi Duet",
    "s3_sub": "Studi Prescription Lisbona",
    "s3_title": "Signature Dynamic Reformer",
    "s3_desc": "Classi di gruppo dinamiche e musicali per forza, resistenza e tono muscolare.",
    "s3_f1": "Playlist Curate ad Alta Energia",
    "s3_f2": "Flusso Dinamico Intermedio e Avanzato",
    "s3_f3": "Disponibile a Saldanha, Alcântara e São Bento",
    "s3_f4": "Prenotabile su ClassPass e Momence",
    "btn_view_schedule": "Vedi Orari in Studio",
    "price_from": "Da",
    "price_per_sess": "/ sessione",
    "price_per_pers": "/ persona",
    "price_studio_pack": "Pack Studio",
    "price_per_class": "/ lezione",
    "rates_tag": "INVESTIMENTO NEL TUO BENESSERE",
    "rates_title": "Listino Trasparente e Pacchetti",
    "rates_subtitle": "Tutte le sessioni private includono analisi posturale, igiene degli attrezzi e monitoraggio dei progressi.",
    "th_format": "Formato Percorso",
    "th_freq": "Frequenza",
    "th_langs": "Lingue",
    "th_rate": "Tariffa",
    "th_action": "Azione",
    "r1_title": "Valutazione Iniziale & Lezione di Prova",
    "r1_desc": "Ideale per iniziare: analisi della colonna e definizione obiettivi (Matwork o Reformer).",
    "r1_freq": "Sessione singola 60 min",
    "r1_badge": "Offerta Lancio",
    "btn_book_trial": "Prenota Prova",
    "r2_title": "Pack Trasformazione 5 Sessioni (Privato)",
    "r2_desc": "Attivazione costante del core, decompressione spinale e tonificazione completa (Mat & Reformer).",
    "r2_freq": "5 sessioni da 55 min",
    "btn_select_pack": "Scegli Pack",
    "r3_title": "Pack Master 10 Sessioni (Privato)",
    "r3_desc": "Riprogrammazione neuromuscolare completa con priorità nella scelta degli orari settimanali.",
    "r3_freq": "10 sessioni da 55 min",
    "r4_title": "Pack Duet 5 Sessioni (Due Persone)",
    "r4_desc": "Attenzione personalizzata a due (a terra o su reformer) – ideale per partner o colleghi.",
    "r4_freq": "5 sessioni da 55 min",
    "btn_book_duet_row": "Prenota Duet",
    "eco_tag": "ECOSISTEMA INTEGRATO",
    "eco_title": "Oltre lo Studio: Podcast, Accessori e Privilegi",
    "eco_subtitle": "Ispirato ai migliori standard europei: audio masterclass, attrezzatura selezionata e convenzioni dedicate.",
    "pod_badge": "Apple Podcasts & Spotify",
    "pod_title": "The Mind & Movement Podcast",
    "pod_desc": "Puntate su fisiologia del movimento, principi di Matwork, postura da ufficio a Lisbona e segreti del Reformer.",
    "pod_track": "Ep. 14: Dalla Danza Classica alla Biomeccanica di Matwork & Reformer",
    "pod_link": "Ascolta su Apple & Spotify →",
    "shop_badge": "Selezione di Veronica",
    "shop_title": "Attrezzatura & Selezione Studio",
    "shop_desc": "Calze grip in cotone organico, teli antiscivolo, cerchi Magic Circle e bande elastiche.",
    "shop_link": "Scopri i Brand Consigliati →",
    "priv_badge": "Convenzioni & Cura",
    "priv_title": "Convenzioni Ballerini & Sanitari",
    "priv_desc": "Sconto cortesia del 15% sulle sessioni private per ballerini professionisti, artisti e personale sanitario.",
    "priv_f1": "Sconto Verificato per Ballerini",
    "priv_f2": "Referral Medici e Fisioterapici",
    "priv_link": "Richiedi Tariffa Convenzionata →",
    "test_tag": "TESTIMONIANZE",
    "test_title": "La Parola alle Allieve di Lisbona",
    "t1_text": "Da expat tedesca a Lisbona, trovare un'insegnante certificata STOTT che parla tedesco e ha vera esperienza di danza classica è stato un sogno. Unire gli esercizi a corpo libero al reformer ha curato la mia schiena.",
    "t1_author": "Elena M.",
    "t1_role": "Executive Tech & Expat, Lisbona",
    "t2_text": "Le correzioni di Veronica sono uniche. Si percepisce immediatamente la sua formazione da ballerina classica: ogni millimetro della postura viene sistemato. Intenso, ma con un'eleganza senza pari.",
    "t2_author": "Sofia R.",
    "t2_role": "Architetto, Chiado",
    "t3_text": "La sua energia sul Reformer da Prescription è mitica, ma le sessioni private 1-a-1 a domicilio hanno portato il mio recupero atletico a un livello superiore.",
    "t3_author": "Marco T.",
    "t3_role": "Triatleta, Cascais",
    "loc_tag": "DOVE FARE LEZIONE A LISBONA",
    "loc_title_1": "Centro di Lisbona & Cascais",
    "loc_title_2": "In studio, a domicilio o online.",
    "loc_p": "Sessioni private nei migliori spazi boutique di Lisbona (Saldanha, Chiado, Santos) o a domicilio su appuntamento.",
    "loc_1_title": "Studi Prescription (Gruppo & Dinamico)",
    "loc_1_desc": "Saldanha · Alcântara · São Bento · Parque das Nações",
    "loc_2_title": "Studio Privato 1-a-1",
    "loc_2_desc": "Spazio boutique esclusivo per corpo libero e reformer con massima privacy.",
    "loc_3_title": "A Domicilio / Cascais & Lisbona",
    "loc_3_desc": "Lezioni personalizzate di Matwork e piccoli attrezzi nella tua residenza.",
    "map_title": "Mappa degli Studi a Lisbona",
    "map_badge": "Disponibile Ora",
    "map_footer": "I messaggi diretti su WhatsApp ricevono risposta entro 2 ore.",
    "contact_tag": "CONTATTO DIRETTO",
    "contact_title": "Inizia la Tua Trasformazione",
    "contact_p": "Scrivi direttamente a Veronica su WhatsApp o compila il modulo per verificare la disponibilità.",
    "ch_1_title": "Risposta Più Rapida su WhatsApp",
    "ch_1_desc": "Chat diretta per concordare gli orari in modo semplice.",
    "ch_2_title": "Lingue Parlate",
    "ch_2_desc": "Italiano, Tedesco, Inglese, Portoghese",
    "wa_btn_text": "Scrivi a Veronica su WhatsApp",
    "form_title": "Richiedi una Consulenza",
    "form_subtitle": "Indica le tue preferenze e ricevi gli orari disponibili entro 24 ore.",
    "lbl_name": "Il Tuo Nome",
    "lbl_email": "Indirizzo Email",
    "lbl_phone": "WhatsApp / Telefono",
    "lbl_interest": "Formato Sessione Desiderato",
    "opt_private": "1-a-1 Pilates Privato (Matwork & Reformer)",
    "opt_duet": "Sessione Duet (2 persone)",
    "opt_trial": "Valutazione Iniziale & Prova",
    "opt_studio": "Classi di Gruppo presso Prescription",
    "lbl_lang_pref": "Lingua di Insegnamento Preferita",
    "lbl_notes": "Obiettivi o Note di Salute",
    "btn_submit_form": "Invia Richiesta di Contatto →",
    "modal_tag": "QUIZ IN 30 SECONDI",
    "modal_title": "Trova il Tuo Percorso di Pilates",
    "modal_subtitle": "Rispondi a 2 veloci domande per scoprire se il formato Privato Mat & Reformer, Duet o Studio fa per te.",
    "q1_title": "1. Qual è il tuo obiettivo primario?",
    "q1_opt1": "Salute della Schiena, Matwork & Allineamento",
    "q1_opt2": "Forza del Core, Resistenza & Condizionamento Atletico",
    "q1_opt3": "Energia Dinamica & Ritmo a Tempo di Musica",
    "q2_title": "2. Qual è il tuo ambiente di pratica preferito?",
    "q2_opt1": "Studio Privato 1:1 o Matwork a Domicilio",
    "q2_opt2": "Duet con Partner o Amica",
    "q2_opt3": "Classe di Gruppo Dinamica in Studio",
    "res_badge": "IL TUO PERCORSO CONSIGLIATO",
    "modal_btn": "Procedi per Prenotare la Sessione Consigliata →",
    "footer_desc": "Hamburg Ballet Academy · Palcoscenici di Berlino · Certificata STOTT Pilates®. Pratica Privata di Matwork e Reformer a Lisbona, Portogallo.",
    "foot_nav_title": "Navigazione",
    "foot_nav_about": "Chi Sono",
    "foot_nav_method": "Il Metodo",
    "foot_nav_sessions": "Formati Privati & Studio",
    "foot_nav_rates": "Listino & Pacchetti",
    "foot_nav_eco": "Podcast & Accessori",
    "foot_loc_title": "Sedi & Studi",
    "foot_loc_sal": "Prescription Saldanha",
    "foot_loc_alc": "Prescription Alcântara",
    "foot_loc_chi": "Studio Privato Chiado",
    "foot_loc_cas": "A Domicilio / Lisbona & Cascais",
    "foot_social_title": "Segui & Connettiti",
    "foot_soc_wa": "WhatsApp Diretto",
    "foot_lang_note": "Classi guidate con fluidità in Italiano, Tedesco, Inglese e Portoghese.",
    "foot_copy": "© 2026 Veronica Sala. Tutti i diritti riservati. Movement Architecture & STOTT Pilates.",
    "foot_crafted": "Sviluppato con precisione per Veronica Sala"
  }
};

let currentLang = 'en';

function setLanguage(lang) {
  if (!i18n[lang]) return;
  currentLang = lang;
  
  // Update buttons state
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.getAttribute('data-lang') === lang);
  });

  // Translate all elements with data-i18n
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (i18n[lang] && i18n[lang][key]) {
      el.textContent = i18n[lang][key];
    }
  });

  // Sync Form language selector
  const langSelect = document.getElementById('langPreference');
  if (langSelect) langSelect.value = lang;
}

document.addEventListener('DOMContentLoaded', () => {
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.addEventListener('click', (e) => {
      const lang = e.target.getAttribute('data-lang');
      setLanguage(lang);
    });
  });

  // Modal Quiz controls
  const modal = document.getElementById('quizModal');
  const openQuizBtn = document.getElementById('openQuizBtn');
  const closeQuizBtn = document.getElementById('closeQuizBtn');

  if (openQuizBtn && modal) {
    openQuizBtn.addEventListener('click', () => {
      modal.classList.add('open');
      resetQuiz();
    });
  }

  if (closeQuizBtn && modal) {
    closeQuizBtn.addEventListener('click', () => {
      modal.classList.remove('open');
    });
  }

  window.closeModal = () => {
    if (modal) modal.classList.remove('open');
  };

  // Sticky Header Effect
  const header = document.getElementById('header');
  window.addEventListener('scroll', () => {
    if (window.scrollY > 40) {
      header.style.boxShadow = '0 8px 24px rgba(28, 25, 23, 0.08)';
    } else {
      header.style.boxShadow = 'none';
    }
  });
});

// Quiz Logic
let quizAnswers = {};

window.quizAnswer = function(question, answer) {
  quizAnswers[question] = answer;
  
  const step1 = document.getElementById('qStep1');
  const step2 = document.getElementById('qStep2');
  const result = document.getElementById('qResult');

  if (question === 'goal') {
    step1.style.display = 'none';
    step2.style.display = 'block';
  } else if (question === 'exp') {
    step2.style.display = 'none';
    result.style.display = 'block';

    const resTitle = document.getElementById('resTitle');
    const resDesc = document.getElementById('resDesc');

    if (currentLang === 'de') {
      if (quizAnswers.goal === 'rehab' || quizAnswers.exp === 'beginner') {
        resTitle.textContent = "1-zu-1 Privates Matwork & Reformer Training";
        resDesc.textContent = "Deine optimale Wahl ist eine individuelle Einzelsitzung mit Veronica (Matte & Reformer) für sichere Gelenkentlastung und präzise Haltungsausrichtung.";
      } else if (quizAnswers.goal === 'flow') {
        resTitle.textContent = "Signature Dynamic Reformer Studio-Klasse";
        resDesc.textContent = "Du liebst Tempo, Rhythmus und Dynamik zur Musik. Entdecke Veronicas Klassen bei Prescription Lissabon.";
      } else {
        resTitle.textContent = "Duett Pilates oder 5er-Transformations-Paket";
        resDesc.textContent = "Die perfekte Kombination aus sportlicher Herausforderung und gezielter Betreuung auf Matte und Reformer.";
      }
    } else if (currentLang === 'pt') {
      if (quizAnswers.goal === 'rehab' || quizAnswers.exp === 'beginner') {
        resTitle.textContent = "Sessão Privada 1-para-1 (Solo & Reformer)";
        resDesc.textContent = "A sua opção ideal é uma sessão personalizada com Veronica para descompressão articular segura e alinhamento milimétrico.";
      } else if (quizAnswers.goal === 'flow') {
        resTitle.textContent = "Aula Signature Dynamic Reformer em Estúdio";
        resDesc.textContent = "Adora energia, ritmo e música contagiante. Experimente as aulas de grupo na Prescription Lisboa.";
      } else {
        resTitle.textContent = "Sessão Duet ou Pack Transformação de 5 Sessões";
        resDesc.textContent = "A combinação perfeita entre desafio atlético e acompanhamento próximo.";
      }
    } else if (currentLang === 'it') {
      if (quizAnswers.goal === 'rehab' || quizAnswers.exp === 'beginner') {
        resTitle.textContent = "Sessione Privata 1-a-1 (Matwork & Reformer)";
        resDesc.textContent = "La tua scelta ideale è una sessione individuale con Veronica per garantire decompressione articolare e allineamento posturale millimetrico.";
      } else if (quizAnswers.goal === 'flow') {
        resTitle.textContent = "Classe in Studio Signature Dynamic Reformer";
        resDesc.textContent = "Ami il ritmo, la musicalità e l'energia fluida. Scopri le classi di gruppo di Veronica presso Prescription Lisbona.";
      } else {
        resTitle.textContent = "Esperienza Duet o Pack Trasformazione 5 Sessioni";
        resDesc.textContent = "La combinazione perfetta tra sfida atletica e coaching personalizzato a terra e su Reformer.";
      }
    } else {
      if (quizAnswers.goal === 'rehab' || quizAnswers.exp === 'beginner') {
        resTitle.textContent = "1-on-1 Private Matwork & Reformer Assessment";
        resDesc.textContent = "Your optimal match is an individualized private session with Veronica. This ensures safe joint decompression, meticulous pelvic alignment, and a bespoke progression.";
      } else if (quizAnswers.goal === 'flow') {
        resTitle.textContent = "Signature Dynamic Reformer Studio Class";
        resDesc.textContent = "You thrive on tempo, choreography, and high-energy music. Check out Veronica's dynamic group sessions at Prescription Lisbon.";
      } else {
        resTitle.textContent = "Duet Pilates or Intensive 5-Pack";
        resDesc.textContent = "A perfect combination of athletic challenge and focused coaching. Book as a duet with a training partner or choose the 5-session transformation pack.";
      }
    }
  }
};

function resetQuiz() {
  quizAnswers = {};
  const step1 = document.getElementById('qStep1');
  const step2 = document.getElementById('qStep2');
  const result = document.getElementById('qResult');

  if (step1) step1.style.display = 'block';
  if (step2) step2.style.display = 'none';
  if (result) result.style.display = 'none';
}

window.handleFormSubmit = function() {
  const name = document.getElementById('name').value;
  const email = document.getElementById('email').value;
  const phone = document.getElementById('phone').value;
  const interest = document.getElementById('interest').value;
  const langPref = document.getElementById('langPreference').value;
  const notes = document.getElementById('notes').value;
  const feedback = document.getElementById('formFeedback');

  let successMsg = "Thank you";
  let btnLabel = "Fast-Track on WhatsApp Now →";
  if (currentLang === 'de') {
    successMsg = "Vielen Dank";
    btnLabel = "Jetzt direkt per WhatsApp anfragen →";
  } else if (currentLang === 'pt') {
    successMsg = "Obrigado";
    btnLabel = "Continuar no WhatsApp Agora →";
  } else if (currentLang === 'it') {
    successMsg = "Grazie";
    btnLabel = "Continua su WhatsApp Adesso →";
  }

  const waMessage = `Hello Veronica! My name is ${name}. I am interested in booking: ${interest}. Preferred language: ${langPref}. Notes: ${notes} (Contact: ${email} / ${phone})`;
  const encodedWa = encodeURIComponent(waMessage);
  const waUrl = `https://wa.me/351912345678?text=${encodedWa}`;

  feedback.style.display = 'block';
  feedback.innerHTML = `<strong>${successMsg}, ${name}!</strong><br><br><a href="${waUrl}" target="_blank" class="btn btn-sm btn-primary" style="margin-top:8px;">${btnLabel}</a>`;
};
